### ISSUE TITLE
Private class names

### ISSUE THREAD

**Issue by denis-sokolov** [css-modules/css-modules#100]
```css
._myBlock {
  display: block;
  border-radius: 5px;
}

.myButton {
  composes: _myBlock;
  cursor: pointer;
}

.myForm {
  composes: _myBlock;
  border: 3px solid blue;
}
```

Here `_myBlock` is an implementation detail that I would like not to publish for my consumers. This is not about minification, this is about encapsulation. I did not find such a feature, and although an underline in the beginning of a file name helps, a native solution would be best.

Possible syntax:

```css
:private .myBlock {
}
```
