### ISSUE TITLE
Selector class substitution.

### ISSUE THREAD

**Issue by CubedEye** [css-modules/css-modules#102]
It would be great if there was a way to substitute class names from other files, possibly with a decorator such as `:ref` or `:alias`. This would allow parent elements to be able to provide a way to style children elements without having to either passing in extra classes or wrap it in extra element just to add extra classes to control it's styling.

**Where is this useful?**

Consider this trivial example when you have a component - for example some sort of `<ButtonControlBar />` that takes a bunch of `<MyAwesomeButton />` components. 

```javascript
<ButtonControlBar>
    <MyAwesomeButton />
    <MyAwesomeButton />
    <MyAwesomeButton />
</ButtonControlBar>
```

The `ButtonControlBar` component wants to add some margin between all of the children so that they are spaced nicely. We're going to want to add 5px of margin to the right of each button except the last. Using straight CSS we could do something like:

```css
.button-control-bar > .my-awesome-button:not(:last-child) {
    margin-right: 5px;
}
```
With CSS Modules we could pass extra classes to each of the children, but in this case the `MyAwesomeButton` component hasn't been implemented with a way to do so (it's something 3rd-party that's also using CSS modules for example). Also we don't know the internal implementation of `MyAwesomeButton` so we can't assume it's just a `<button>` element.

We could instead wrap each of the children component in another element that you can add a class to allow use to control the style of the children, but this is just unnecessary wrapping to avoid what would be fairly straight forward with straight CSS `.button-control-bar > .my-awesome-button`.

**Proposed Implementation**

We could introduce a `:ref` pseudo-class that would allow us replace a selector value. I'm a fan of the pseudo-class as a declarative way to use the imports to replace classes. It's also less "magic" that just straight replacing the .childButton class where ever it appears.

```css
// MyAwesomeButton.css-module
.my-awesome-button {
    background: red;
}

:export {
    myAwesomeButton: my-awesome-button
}

// ButtonControlBar.css-module
:import(MyAwesomeButton.css-module) {
    childButton: myAwesomeButton
}

.button-control-bar > :ref(.childButton):not(:last-child) {
    margin-right: 5px;
}
```

This provides a fairly fuss free way to achieve the above, with the added bonus that if we don't want to use `MyAwesomeButton` anymore, because `<NextBigThingButton/>` component is the more suited to the project we can just fix up the `:import` and the rest of the CSS doesn't need to be touched.

```css
// NextBigThingButton.css-module
.next-big-thing-button {
    background: red;
}

:export {
    nextBigThingButton: next-big-thing-button
}

// ButtonControlBar.css-module
:import(NextBigThingButton.css-module) {
    childButton: nextBigThingButton
}

.button-control-bar > :ref(.childButton):not(:last-child) {
    margin-right: 5px;
}
...more rules that are using :ref(.childButton)
```

**Comment by nkbt** [comment]
Personally I would actually pass classes down or wrap them. Simple, no extra language necessary, no extra complications.

```js
<ButtonControlBar className={css.bar}>
    <MyAwesomeButton className={css.bt} />
    <MyAwesomeButton className={css.bt} />
    <MyAwesomeButton className={css.bt} />
</ButtonControlBar>
```

```css
.bar {}
.bt:not(:last-child) {
  margin-right: 5px
}
```

Can't figure out how it might be more difficult. Do I miss something?

**Comment by KJTsanaktsidis** [comment]
I think in our case, the reason why we don't want to add classes to the children is because often the children are passed in. Consider something like the `ButtonControlBar`...

```jsx
// ButtonControlBar.js
const css = require('buttonControlBar.css');
const ButtonControlBar = React.createClass({
    render() {
        return (
            <div className={css.bar}>
               {this.props.children}
            </div>
        );
    },
});
```jsx
// SomeThingWithAButtonBar.js
const Thing = React.createClass({
    render() {
        return (
            <ButtonControlBar>
                <MyAwesomeButton text='foo' />
                <MyAwesomeButton text='bar' />
            </ButtonControlBar>
        );
});
```

In the above example, the button control bar expects to be passed buttons as children. There are, as you point out, a few ways to skin this cat:

* The consumer of the `ButtonControlBar` could put a class on the `MyAwesomeButton`s it creates. However, the fact that the button needs special styling inside the bar is really the bar's business, not the consumers, and it feels wrong to pollute the consumer with this responsibility
* The ButtonControlBar could wrap each of its children in a div with a class. However, this introduces an extra level of DOM where it isn't strictly needed
* The ButtonControlBar could clone each of its children and put a className on it. However, if the consumer also wanted to put a class on the button (because I want a purple button!) then the cloning process would have to take care to merge the `className` prop correctly (and this isn't automatic anymore with `React.cloneElement` the way it used to be with `cloneWithProps`). This seems like a good way to spend 10 minutes scratching your head wondering why your button is the wrong colour.

I think the most elegant way to solve this problem is to just make use of the class that's already there! No extra DOM and no confusing prop merging.

**Comment by nkbt** [comment]
I think it is not very nice conceptually. If you render children 'blindly'
then it implies you have no idea about them, so you should not style them.

If your wrapper supposed to know about them, you would then iterate through
children and clone each with some extra props added. Like extra class added.

I still think it is not a styling (css, css modules) concern.

**Comment by KJTsanaktsidis** [comment]
Hey, just wondering if anybody has any more input about this idea?

**Comment by renanvalentin** [comment]
Hello guys, how did you ended up to solve this problem? I'm thinking in other workarounds but it seems too complicated, like having to pass props to child components.

**Comment by KJTsanaktsidis** [comment]
@renanvalentin we're using our fork webpack/css-loader#212 in production :)

**Comment by renanvalentin** [comment]
I've came up with a solution, it is more philosophical than technical:
```javacript
<ButtonControlBar>
    <MyAwesomeButton />
</ButtonControlBar>
```
```
.button-control-bar > .my-awesome-button {
   margin: 20px;
}
```
or

```
.button-control-bar > button {
   margin: 20px;
}
```
Suppose I want to add an extra margin to my children buttons, that css selector should be fine, but thinking about components, thats an a bad idea, because:

-> I need to know what class I'm using inside my component
-> What if I change my HTML markup or changed the class name inside the component, this will result in breaking that css selector chaining;

So I wrote this  "Layout Component" responsible for extend my components:

```javascript
class Layout extends React.Component {
  componentDidMount() {
    let node = ReactDOM.findDOMNode(this);
    node.classList.add(this.props.className);
  }

  render() {
    return this.props.children;
  }
}
```

And I'm using it in this way:

```javascript
<ButtonControlBar>
     <Layout className={classes['pull-right']}>
         <MyAwesomeButton />
      </Layout>
</ButtonControlBar>
```

While I was writing this, I saw lots of problems on it, but that's ok hahahaha

**Comment by meta-meta** [comment]
Say I have the following React components:

ModuleA renders
```html
<div styleName="moduleA">
    {props.children}
</div>
```

ModuleB renders
```html
<div styleName="moduleB"/>
```

and some markup:
```html
<div>
    <ModuleA>
        <ModuleB/>
    </ModuleA>
    <ModuleA>
        <ModuleB/>
    </ModuleA>
    <ModuleA>
        <ModuleB/>
    </ModuleA>
    [...]
</div>
```

```scss
.moduleB { 

}

.moduleA {
  &:nth-child(even) {
    .moduleB { /* doesn't work because the real classname of ModuleB is not known in ModuleA*/
      background-color: #000;
    }
  }

  &:nth-child(odd) {
    .moduleB  {
      background-color: #fff;
    }
  }
}
```

What's the idiomatic css-modules approach to this? Pass odd/even classnames into ModuleB props?
