### ISSUE TITLE
Imports can unexpectedly stomp on CSS

### ISSUE THREAD

**Issue by CubedEye** [css-modules/css-modules#105]
When importing other css-modules using `:import(...){}` syntax you can get some unexpected results, if you are not careful.

Consider the following:

``` css
// myComponent.css-module
@media print {
    .myComponent {
         background: red;
    }
}
```

This does what you expect, the background is red, when printing. However, if someone comes along and imports something at the top of the files and uses print as one of the variables the output is not what you're expecting looking at the code.

``` css
// myComponent.css-module
:import("myVariables.css-module"){
    print: myPrintVar
}
@media print {
    .myComponent {
         background: red;
    }
}
```

ends up outputing to something like

``` css
@media [value of myPrintVar] {
    .myComponent {
        background: red;
    }
}
```
