### ISSUE TITLE
Nesting and js interop

### ISSUE THREAD

**Issue by blainekasten** [css-modules/css-modules#112]
At Hudl, we are currently trying to find a standard for classnames when interoping css modules to javascript modules. When looking at common css architecture patterns, it's typical to describe a component via a name, then modifiers or element descriptors.

I'm wondering if the interop spec could handle nesting and make this easier. Currently we're looking at doing something like this:

``` css
:local(.fooBar) { /* component */ }
:local(.fooBar_descriptor) { /* element */ }
:local(.fooBar_descriptor$modifier) { /* modifier */ }
```

This works with JS but is kind of awkward to see inside of js.

``` js
import style from './style.css';

style.fooBar // normal
style.fooBar_descriptor // sort of awkward
style.fooBar_descriptor$modifier // really awkward
```

Since things like BEM, SMACSS, etc have been invented for good reason, I have a proposal that could make this interop easily.

I'll rewrite the above in the proposal.

``` css
:local(.fooBar) {
  /* component */

  :local(.descriptor) {
    /* descriptor */

    :local(.modifier) {
      /* modifier */
    }
  }
}
```

This would then generate a style object like so

``` js
import style from './style.css';
console.log(style);
// prints 
// { fooBar: { descriptor: { modifier: <hash> } } }
```

This effectively makes the dot syntax our separator. This would then work by hashing the objects to get the obfuscated classNames. Since each part of the object will be unique, there won't be any name clashing. For example, the above css could compile to this:

``` css
/* hash of  { descriptor: { modifier: <hash> } } */
.Asjz8sf23$2a {
  /* component */

/* hash of  { modifier: <hash> } */
.Deaf89a8fy88 {
  /* descriptor */
}

/* hash of  'modifier' */
.jasDD234akl {
  /* modifier */
}
```

This allows developers to make localized modules, with meaningful and descriptive naming schemes for all levels of describing their components.
