### ISSUE TITLE
:global not working for animate.css

### ISSUE THREAD

**Issue by huarse** [css-modules/css-modules#115]
I want to import animate.css as a global style, but it will add suffix on the class. Then I use :global to wrap the import, and it works on class names, but the @keyframes still has suffix.

**Comment by huarse** [comment]
I find that :global is not working for @keyframes, not just on @import.

**Comment by ticketdirectory** [comment]
Did you manage to overcome this issue @huarse ? We're experiencing the same.

**Comment by chapati23** [comment]
same here.

Input:
```css
:global {
  @keyframes spin {
    0% {
      transform: rotate(0);
    }
    100% {
      transform: rotate(359deg);
    }
  }
}
```

Expected Output:
```css
@keyframes spin {
    0% {
        transform: rotate(0);
    }
    100% {
        transform: rotate(359deg);
    }
}
```

Actual Output:
```css
@keyframes src-___index__spin___uB5Zv {
    0% {
        transform: rotate(0);
    }
    100% {
        transform: rotate(359deg);
    }
}
```

**Comment by chapati23** [comment]
not a fix but a workaround (or just the recommended way to do it after all?):
https://css-modules.github.io/webpack-demo/

so instead of the above i now do:

```css
# shared/animations.css
@keyframes spin {
    0% { transform: rotate(0); }
    100% { transform: rotate(359deg);}
}

.spin {
  animation: spin 2s infinite linear;
}
```

and then use it via:

```css
# componentX.css
.spinner {
    composes spin from '../../....../shared/animation.css'
}
```

which is ok IMO but the thing i really dislike is the hard coupling and ugly traversing through your project-tree. change one hierarchy-level later on and have yourself a little pathfixing-session…

**Comment by eriklharper** [comment]
Wrapping the @keyframes rule in a :global call worked for me:

```
@keyframes :global(zoomBounceIn) {
  0% {
    transform: scale(0);
  }
  50%{
    transform: scale(1.1);
  }
  70% {
    transform: scale(0.9);
  }
  100% {
    transform: scale(1);
  }
}
```

**Comment by derpoho** [comment]
Altough @eriklharper`s solution does compile, but i get a warning when using it with webpack 2 and sass-loader!

**Comment by eriklharper** [comment]
@derpoho sounds like you may have to adjust the order in which your compilations happen.  CSS Modules needs to do its thing first before Sass can work on it.

**Comment by derpoho** [comment]
Tried that, i changed the order in any direction, the warning stays, just uncommenting the resolve-url-loader helped. But that`s not a long term solution ;)

```
  'style?sourceMap=true',
  'css?modules=true&importLoaders=true&localIdentName=[name]__[local]_[hash:base64:5]',
  // 'resolve-url',
  'sass?sourceMap=true',
```

**Comment by shahata** [comment]
+1 is there a fix for this on the horizon?

**Comment by faceyspacey** [comment]
@eriklharper the only issue is you can't actually use the animation name, i.e. this won't work:

```
.myClass {
  animation: :global(myAnimation) 1s
}
```

`myAnimation` won't compile.

**Comment by eriklharper** [comment]
@faceyspacey does omitting the `:global` portion like this make it work?

```
.myClass {
  animation: myAnimation 1s
}
```
Because `myAnimation` is a global, you should just be able to name it directly in the call site of your `myClass` rule.

**Comment by farzer** [comment]
meet the same case

**Comment by NSLS** [comment]
Having a similar issue with css-loader combined with less-loader.
`@keyframes :global(name)` throws an error and there is no other way to make a global animation

**Comment by ioanlucut** [comment]
+1

**Comment by AshCoolman** [comment]
+1

**Comment by Azein** [comment]
In fact, I can't use any of approaches - not :global nor :local for animation names in my build process - either nothing good being compiled, or there is a "Module build failed - double colon" error. I still can add animation name as a string - like animation-name: 'checkbox__blink'; Where 'checkbox' is the ident__name. Yet this works only in chrome. I have no idea why this issue receives pretty little attention because it's kinda critical.

**Comment by eriklharper** [comment]
Considering the age of this thread, its a good idea for you to provide exact version numbers that you're working with @Azein

**Comment by Azein** [comment]
@eriklharper 
I continued to research my issue and well, problem was caused by postcss-composes plugin - somehow it intercepted css-loader module processing and crashed the build because mentioined double colon error.
If anyone would encounter something alike - it is worth to check composing/imports plugins. Thanks everyone for attention =)

**Comment by TrySound** [comment]
Keyframes behavior was separated and simplified
https://github.com/css-modules/postcss-icss-keyframes

**Comment by yolo2013** [comment]
I think this issue should be reopen. It is a bug. I will try to fix it.

**Comment by TrySound** [comment]
@yolo2013 in new version :global/:local behavior was removed for keyframes. They are always local, until you disable keyframes plugin. Local identifier will be applied to animation name only if there's keyframes in the scope.

**Comment by Peterabsolon** [comment]
Anyone found a solution to have keyframes animation applied to global class? Shouldn't this issue be opened?

**Comment by TrySound** [comment]
@Peterabsolon Do you have local enabled by default?

**Comment by Peterabsolon** [comment]
@TrySound Yes, I do. Thing is, I need to set the animation to a global class. I tried using "compose" css property but it doesn't work together.

**Comment by TrySound** [comment]
@Peterabsolon Try to use [postcss-icss-selectors](https://github.com/css-modules/postcss-icss-selectors) and [postcss-icss-keyframes](https://github.com/css-modules/postcss-icss-keyframes), but disable modules in css-loader.

**Comment by kud** [comment]
I'm using `react-placeholder` and it works like a charm:

```js
import "react-placeholder/lib/reactPlaceholder.css"
import styles from "./index.module.css"
```

```css
/* index.module.css */
@keyframes :global(react-placeholder-pulse) {
  0% {
    opacity: .2;
  }

  50% {
    opacity: .7;
  }

  100% {
    opacity: .2;
  }
}
```

**Comment by nsaubi** [comment]
If anyone is still searching, this is working :
`.connection_lost{
  color:red;
  :global{
    animation: 2s infinite alternate color_change;
  }
}

@keyframes :global(color_change) {
  from { color: rgba(200,0,0,0); }
  to { color: rgba(200,0,0,1); }
}`

**Comment by sumthief** [comment]
Workaround with `@keyframes :global(NAME-OF-YOUR-ANIMATION)` works good for me. But before checking the result ensure that you moved out your `@keyframes` blocks out of wrapping :global scope.
**It don't works for me**
<pre>:global { 
 /**
  * Usual styles such as .selector { color: red; }
 /*

 @keyframes :global(ANIMATION-NAME) {
   // Keyframes description.
 }
}</pre>
Because all my keyframes was wrapped in extra { } in <style> tag.
**It works for me**
<pre>
:global {
 /**
  * Only usual styles such as .selector { color: red; }
 /*
}
 @keyframes :global(ANIMATION-NAME) {
   // Keyframes description.
 }
</pre>

**Comment by impressor615** [comment]
I am using semantic-ui for my project and also css-loader modules options too. This disable my semantic-ui default animation. Any solution for this? I think this problem is still going on.

**Comment by omichelsen** [comment]
For anyone using LESS this hack makes the above hack work:

```
@keyframes ~":global(ANIMATION-NAME)" {
   // Keyframes description.
 }
```

**Comment by mohammadalipak** [comment]
If you're looking for a **plain css** solution, I modified [@nsaubi's solution above](https://github.com/css-modules/css-modules/issues/115#issuecomment-337824036) to:

```css
.connection_lost{
  color:red;
}

.connection_lost :global{
  animation: 2s infinite alternate color_change;
}

@keyframes :global(color_change) {
  from { color: rgba(200,0,0,0); }
  to { color: rgba(200,0,0,1); }
}
```

**Comment by brendanfalkowski** [comment]
For reference, I found this issue while debuggin and documented several approaches here: https://gravitydept.com/blog/keyframe-animations-in-css-modules

**Comment by antitoxic** [comment]
@brendanfalkowski thanks for the article!

```scss
<selelctor> :global{
  animation: .... somename;
}

@keyframes :global(somename) {
 ...
}
```

seems to me to be the simplest solution for cross-file referencing.

**Comment by pascalduez** [comment]
Found a workaround recently, I needed the opposite (get le local name).

```css
@value fadeIn: :local(fadeIn);

:root {
  --animation: fadeIn 400ms;
}

@keyframes fadeIn { ... }
```

So it could totaly work the other way round.
