### ISSUE TITLE
Import order when composing multiple classes

### ISSUE THREAD

**Issue by Ambroos** [css-modules/css-modules#12]
Imagine:

```css
// a.css
.a { color: #aaa; }
```

```css
// b.css
.b { color: #bbb; }
```

```css
// ab.css
.ab {
    composes: a from './a.css';
    composes: b from './b.css';
}
```

```css
// ba.css
.ba {
    composes: b from './b.css';
    composes: a from './a.css';
}
```

```javascript
# ab.js
import ab from './ab.css';

render() {
    return <div class={ab.ab}>AB</div>;
}
```

```javascript
# ba.js
import ba from './ba.css';

render() {
    return <div class={ba.ba}>BA</div>;
}
```

You'd expect `AB` to always be `#bbb` (because b gets imported last), and `BA` to always be `#aaa` for the same reason. If you look at both JS files independently, that is. However, since you depend on import order (which can be affected by other imports happening anywhere in the same codebase), you lose control over the inheritance.

This is fine-ish when you know your codebase and can be sure that CSS is always imported in the right order, but the moment someone imports `b.css` before you get the chance to import `a.css` first, you lose the expected result.

With preprocessors and things like `@extends` you don't get this issue because imports just flow linear and deciding what CSS comes first is a lot more explicit. Their documentation explicitly says that the order of inheritance is purely defined by when selectors occur in the CSS.

There's a way to fix this, but it means adding specificity tricks, and adding selectors to the imported CSS selector in the output.

Using the examples above, it'd lead to this (no class name mangling for clarity, [together in a gist](https://gist.github.com/Ambroos/e80806b50faa213832cd)):

```css
.a, .a.ab-a-specific, .a.ba-a-specific.ba-a-specific-specific { color: #aaa; }
.b, .b.ab-b-specific.ab-b-specific-specific, .b.ba-b-specific { color: #bbb; }
```

```html
<div class="ab a ab-a-specific b ab-b-specific ab-b-specific-specific">AB</div>
<div class="ba b ba-b-specific a ba-a-specific ba-a-specific-specific">BA</div>
```

The good things: it works, repetition gzips well. The bad thing: it's ugly, a challenge to implement.

In projects with lots of composing this could lead to huge selectors, since you're basically replacing all inheritance-by-inclusion-order with explicit specificity. Luckily it's only necessary once you start dealing with composing from multiple classes in a single new class, so maybe it's still something to consider? It would vastly increase complexity of the code, since any class would cause new selectors to be added to all classes it composes from and all their parents too, all the way up the tree.

The other option is probably just making no guarantees about import/override order when dealing with composing from multiple classes. Which is also not ideal and basically means it's an unreliable feature.

Maybe I'm thinking too far here, but I think it's something to look into, at least.

**Comment by sokra** [comment]
Yes, we already discussed this problem. see https://gitter.im/css-modules/css-modules?at=556b2cada18520fe7a59149d and prev comments.

I think we decided to add this as "undefined behavior" in the spec.

In summary: When you `compose` multiple classes that have conflicting properties the behavior is undefined.

Design your classes to do a single thing and it should not occur that classes have conflicting properties. In exceptional cases `!important` helps...

**Comment by geelen** [comment]
Actually @sokra (apologies for not catching this when it was reported), I think we can and should define an order for imports. I've actually written code for both the loader core (for Browserify) and the JSPM loader to do this (relevant PR: https://github.com/geelen/jspm-loader-css/pull/12)

Basically, here are the rules:

1. Each file is injected as its encountered *except*
2. Dependencies are injected *above* their parents *and*
3. A file can be injected only once

So, if `ab.js` is included before `ba.js`, `ab.css` is encountered first, its dependencies are injected above it *in the order they are encountered* so `a.css` then `b.css`. Once `ba.css` is encountered, `a.css` and `b.css` are already injected so nothing happens. Result, they both get `#bbb`.

This is *exactly* the same as using `@extend`, i.e. **source order is everything** :smiley:

**Comment by sokra** [comment]
> Each file is injected as its encountered except
> Dependencies are injected above their parents and
> A file can be injected only once

yes, but we are talking about the case when there is a conflict.

i. e. 

for a module

``` css
// ab.css
.ab {
    composes: a from './a.css';
    composes: b from './b.css';
}
```

You cannot promise the user that `a.css` is before `b.css`, because there could a another module which is imported before `ab.css` with the following content:

``` css
// ba.css
.ba {
    composes: b from './b.css';
    composes: a from './a.css';
}
```

---

Because of this the spec says the order of multiple imports is undefined. In 99% the order is the source order, but we can't promise that for every case. The spec only tells you that you should not rely on this!

**Comment by Ambroos** [comment]
I think that with code splitting and on-demand loading you can't even count on import order app-wide. Imagine if clicking one button loads `ab.css` and clicking another loads `ba.css`, depending on which button you click first you'd get different output.

How realistic would adding the specificity-boosting selectors be? It looks like it'd a lot of work to implement for tiny edge cases, but once it's there you have the enormous advantage of having 100% guaranteed CSS inheritance... I don't think that's something that's been done before.

**Comment by sokra** [comment]
> How realistic would adding the specificity-boosting selectors be? It looks like it'd a lot of work to implement for tiny edge cases

This would be a global transform, because you would need a global view on all CSS Modules.

I don't like global transforms...

**Comment by andreypopp** [comment]
We did implement specificity-boosting in [react-style](https://github.com/js-next/react-style/blob/master/lib/stylesToCSS.js#L74) which resulted in bloated class properties of DOM elements. css-modules has an advantage is that compositions are statically defined (in react-style you can compose style at runtime) and so specificity boosters can be activated only where needed.

**Comment by andreypopp** [comment]
> This would be a global transform, because you would need a global view on all CSS Modules.

You can actually always generate specificity boosters while in dev and implement more complex algorithm as optimisation for prod build.

**Comment by geelen** [comment]
I am 100% against any kind of specificity-boosting for this feature. CSS has always worked like this, and CSS modules is about enabling useful JS functionality without departing too far from CSS semantics.

Maybe there's a better way to conceptualise `composes`. Consider the following:

```css
/* foo.css */
.foo {
  composes: a from "./a.css";
  composes: b from ".b.css";
  color: blue;
}
```

If this was JS, this might mean:

> - Load everything from `a` in `a.css`
> - Then `Object.merge` everything from `b` in `b.css`
> - Then `Object.merge` all the inline styles from `.one`
> - Then take all those styles and add them to every element marked as `foo`.

**But this is CSS**, so really it means:

> - All `foo`s are also `a`s and `b`s, so include their classes as well when you see `foo`
> - Load `a` from `a.css` and load `b` from `b.css`
> - Ensure `.a` and `.b` appear in the DOM above `.foo` so `.foo` can override

The order of `.a` and `.b` in the DOM *is* specified, it's just specified by the order in which they're *first* encountered, that just may not be the component you're currently looking at :smile: 

---

There's a far simpler solution though that has clearer semantics for both computers and humans:

```css
/* a.css */
.a { color: #aaa; }
```
```css
/* b.css */
.b { composes: a from "./a.css"; color: #bbb; }
```
```css
.foo {
  composes: b from ".b.css";
  color: blue;
}
```

Even if `b.css` is loaded first, its dependency on `a.css` will ensure that `.a` *always* gets injected above it, and the behaviour is totally fixed and explicit.

For me, having two unrelated classes both setting (and competing for precedence over) the same property has long been a CSS smell, and CSS Modules lets you define which is the base style and which should be considered an override, which I think is neat!

**Comment by NogsMPLS** [comment]
This started to be an issue for us on a large and complex React UI Component library we are building internally. We were using small reusable classes, like in Basscss, to compose almost all of our styles. But we kept running into an ```Order in extracted chunk undefined``` error. Sometimes this was because of ```composes``` order, sometimes this was because of javascript import order of components.

Basically, in the library and any app that may use the library we were unable to guarantee import order in javascript, and also frustrations with having no way to enforce 'composes' order convention across many many files, except for getting a build error and then rearranging.

The way we solved this internally was, instead of having multiple css files and composing from them like this:
```css
.someClass {
    composes: red from '../styles/colors.css';
    composes: block floatLeft from '../styles/layout.css';
}
```
We instead have 1 style.css file that has a series of imports, thus ensuring composes/import order at all times. So the same class would look something like:
```css
.someClass {
    composes: red from '../styles.css';
    composes: block floatLeft from '../styles.css';
}
```
and then styles.css would either be 1 css file with the shared amicro/atomic classes in it, or better yet, would just have a series of imports thus keeping shared styles structurally separate, but without the issue of having to worry about order of composes input. So styles.css could look like:
```css
@import './styles/colors.css';
@import ./'styles/layout.css';
```
This solution admittedly relies on PostCSS Import plugin, so I understand it may not be a solution for all situations. I just wanted to document another possible way to tackle composes and import order issues, that so far seems to have fixed things for us.
