### ISSUE TITLE
Add warnings about using composes conditionally in media queries

### ISSUE THREAD

**Issue by skitterm** [css-modules/css-modules#126]
I've read #33, in which Glen provided a nice solution to composition in media queries:

``` css
@media (max-width: 1100px) {
.make-me-red {
    color: red;
  }
}
.link {
  composes: make-me-red;
}
```

I tried the "this won't work" example and found unexpected behavior. I expected it to not work, but I thought it would blow up with the "only single selector allowed" message. Instead, the <code>.normal</code> element now **always** has the text colored red, even when the window is wider than 1100px:

``` css
.make-me-red {
  color: red;
}

@media (max-width: 1100px) {
  .normal {
    composes: make-me-red;
  }
}
```

I would have expected that the <code>.make-me-red</code> class would have **never** been added to the element (since it looks like it'd only get composed when narrower than 1100px), but I appear to have been mistaken.

So does <code>compose</code> always add the class name to that element on a media query, even when the media query's conditions are not met? I understand that the classes returned to the element are static, but I would have expected the class not to get passed to the element at all (since it is conditional). It fails silently, or a sort, unlike the nice error experience that I get when I try to compose on a <code>:hover</code> state or something.
