### ISSUE TITLE
Should compose-only classes be hidden?

### ISSUE THREAD

**Issue by BaoDelta** [css-modules/css-modules#127]
Let's say I have the following code:

``` css
/* test.css */

.roundedBorder {
  border-radius: 5px;
}

.redBorder {
  border: 1px solid red;
}

.roundedAndRedBorder {
  composes: roundedBorder;
  composes: redBorder;
}
```

``` js
/* test.js */
import styles from './test.css'

console.log(styles)
```

When I run the code with style loader and css loader, the output is:

``` json
{
  "roundedBorder": "test__roundedBorder",
  "redBorder": "test__redBorder",
  "roundedAndRedBorder": "test__roundedAndRedBorder test__roundedBorder test__redBorder"
}
```

and the style element added into DOM is:

``` html
<style type="text/css">
.test__roundedBorder {
  border-radius: 5px;
}

.test__redBorder {
  border: 1px solid red;
}

.test__roundedAndRedBorder {
}
</style>
```

The class roundedAndRedBorder is used here only to compose the two other classes. Therefore, I think we should not have the class test__roundedAndRedBorder in the output. What do you think?

**Comment by joeybaker** [comment]
@BaoDelta It's not a bad idea. But, you could use something like [cssnano](http://cssnano.co/) to eliminate the empty classes. Though, it's a good argument that removing empty classes could be added to CSS Module's list of core modules. I can't think of any "unsafe" behavior that would occur.

**Comment by BaoDelta** [comment]
Thanks for your answer @joeybaker

If I add `minimize` to css-loader query, the class `test__roundedAndRedBorder` is not in the style element anymore but is still referenced in `styles.roundedAndRedBorder`. In addition, if I have a css file with only compose-only classes, then I will have an empty style element in the DOM.

My situation is that I'm using [purecss](http://purecss.io/) in my project but I want to hide that fact from my React components. They should not know which css framework I'm using so that I can change and tweak the css. Therefore, I have a lot of css modules with compose-only classes like this:

``` css
/* Button.css */

.button {
  composes: pure-button from global;
}
```

That produces a lot of empty and unused **real** classes.
