### ISSUE TITLE
Overriding Bootstrap/other style library styles

### ISSUE THREAD

**Issue by skitterm** [css-modules/css-modules#128]
I'm planning on using Bootstrap and CSS Modules on a project. One issue I see is how to override a bootstrap style rule with one in CSS Modules. Since CSS modules only provide one class to a style rule, specificity would indicate that I can't override a bootstrap style rule with more than just one class with a CSS Modules one. Most styles could be overridden (since most are just using one class name), but some could not. Example: 

Bootstrap style:
```css
.dropdown-menu > li > a {
  /* some sample style */
  color: blue;
}
```

CSS Modules-outputted style:
```css
/* won't override due to specificity */
.my-app___auto__genereated__unique-classname {
  color: red;
}
```

I realize that overriding by IDs or using <code>!important</code> is a bad idea, but how do you override styles from other libraries that use two classnames, or a classname and a tag selector? I realize I could write some global css to override, but I obviously want to stay away from that (that's why I'm using CSS Modules).
