### ISSUE TITLE
Is there support bi-directional composition?

### ISSUE THREAD

**Issue by chemoish** [css-modules/css-modules#136]
``` scss
/// link.scss
.link {} // a link that looks like a link
.link--button-link // a link that looks like a button styled as a link
{
  composes: button--link from './button.scss';
}
```

``` scss
/// button.scss
.button {} // a button looks like a button
.button--link // a button looks like a button styled as a link
{
  composes: button;
  composes: link from './link.scss';
}
```
