### ISSUE TITLE
Override child component styles (API suggestion)

### ISSUE THREAD

**Issue by elado** [css-modules/css-modules#139]
Let's say I have a `<MyComponent>` and `<MyList>` that contains a list of `<MyComponent>`.

Only when in under `<MyList>`, I want `<MyComponent>` to have some different styles, maybe `flex`, or a different `background-color`. `flex` is a good example because `MyList` may have `display: flex` and might want its children to have `flex: 25%` and also stretch vertically.

Currently it doesn't seem like I can override `<MyComponent>` that is nested under `<MyList>`, as I would with regular css.

Here's a suggestion (I posted in https://github.com/gajus/react-css-modules/issues/94 but it might make more sense here):

```scss
// MyComponent.scss
.component {
  background-color: yellow;
  font-weight: bold;
}

// MyList.scss
.list {
  // ...
}

.listItem {
  border: 1px solid blue;
}

.listItem {
  // ▼ this will generate ".listItem_[hash] .component_[hash] {}" rule instead of just .listItem_[hash]
  override-child: component from './MyComponent.scss';
  background-color: red;
}
```

```jsx
// MyComponent.jsx
import styles from './MyComponent.scss'
export default ({ title }) => <div className={styles.component}>{title}</div>

// MyList.jsx
import styles from './MyList.scss'
export default ({ titles }) => (
  <div className={styles.list}>
    {titles.map(title => <div key={title} className={styles.listItem}><MyComponent title={title} /></div>)}
  </div>
)
```

And ideally that would work in all hierarchies. If I have `<MyButton>` in `MyComponent`, I can affect if from `.MyList.scss`:

```scss
.listItem {
  // ▼ this will generate ".listItem_[hash] .component_[hash] .button_[hash] {}" rule
  override-child:
    component from './MyComponent.scss',
    button from './MyButton.scss';
  font-size: 17px;
}
```

I read the suggestions by @joeybaker here: https://github.com/css-modules/css-modules/issues/21#issuecomment-121306225 but I think there should be a better way.

Thoughts?

**Comment by liady** [comment]
(Reposting my comment from react-css-modules discussion)  
@elado +1 that's a very good idea. The reference can even be in the selector level:

```css
// MyList.scss
.listItem :external(.button from './MyButton.scss') {
  font-size: 17px;
}
```
And that way even the child element can have a specific rule for when it is inside a container:
```css
// MyButton.scss
:external(.listItem from './List.scss') .button {
  font-size: 17px;
}
```

**Comment by SohKai** [comment]
@elado So you can accomplish your first example right now if you allow your `MyComponent` to take in a classname (or entire style object) as a prop and apply it on itself, and then in `MyList`, create a class that composes the class from `MyComponent` with the override and then pass the new class back to `MyComponent`. This is essentially what @joeybaker suggested as approach 2:

```scss
// MyComponent.scss
.component {
  background-color: yellow;
  font-weight: bold;
}

// MyList.scss
.listItemChild {
  composes: component from './MyComponent.scss';
  background-color: red;
}
```

```js
// MyComponent.jsx
import styles from './MyComponent.scss'
export default ({ className, title }) => (
    <div className={className ? className : styles.component}>{title}</div>
);

// MyList.jsx
import styles from './MyList.scss'
export default ({ titles }) => (
  <div>
    {titles.map(title => (
        <div key={title}>
            <MyComponent className={styles.listItemChild} title={title} />
        </div>
    ))}
  </div>
);
```

Not that I dislike what you're proposing, since it would certainly be convenient at times, but on some level I do feel like this kind of goes against some of the things that CSS modules was designed to protect you from. Although it's always on the user to responsibly use the provided tools, allowing for child overrides would get us closer to the messy world of normal CSS's spaghetti overrides.

It's a little more complicated, but in something like your case with flexbox, or specific style overrides, what if you made a base component that had the common styles and then put a shim component around the base component that added the positional / spacing styles, or any other specific style overrides with the class names approach above? If necessary, the shim component could also be made more generic with props. Alternatively, sometimes these overrides are because of theming (ie. override colors and whatnot) and maybe building functionality (such as HOCs in React) to switch between themes would be more idiomatic.
