### ISSUE TITLE
@keyframes xxx is transformating too

### ISSUE THREAD

**Issue by NN77** [css-modules/css-modules#141]
Hi, have some problem with:

`````` css
/* input */
@keyframes anim {
    50% {
      left: 56px;
    }
  }
```css
/* output */
...
animation: _anim_ljlgu_1 1s infinite linear;
...
``````

**Comment by joshwnj** [comment]
Hi @NN77 , this is expected behaviour from what I understand. Keyframe names are also within global scope, so unless they are given a unique name there is the chance of an unintended collision.

**Comment by ouqinglai** [comment]
Did you solve it?

**Comment by ouqinglai** [comment]
`/* input */
:global {
	.test {
		:local {
			animation: name .6s ease;	
		}
	}
}
@keyframes name {
	//
}
/* output */
.test {
  animation: name-2j99k .6s ease;
}
@keyframes name-2j99k {
	//
}`

**Comment by mnpenner** [comment]
Has anyone got this working with LESS?

Input:

```less
:local {
    .spin {
        animation: spin .5s infinite linear;
    }

    @keyframes spin {
        0% {
            transform: rotate(0deg);
        }
        100% {
            transform: rotate(360deg);
        }
    }
}
```

Out:

```
._1JvaUPKhMxOEcthB0QSfsP {
  animation: _1JvaUPKhMxOEcthB0QSfsP .5s infinite linear;
}
@keyframes spin {
  0% {
    transform: rotate(0deg);
  }
  100% {
    transform: rotate(360deg);
  }
}
```

Why doesn't `@keyframes spin` get translated too?

I can work around this for now by making my animation global:

```less
    .spin {
        :global {
            animation: spin .5s infinite linear;
        }
    }
```

But I actually *do* want the keyframes name randomized.

**Comment by lennerd** [comment]
Any progress with this?

**Comment by xingbofeng** [comment]
like my code, you can solve the problem.
```css
@keyframes :global(slideInFromRight) {
  0% {
    transform: translateX(100%);
  }
  100% {
    transform: translateX(0);
  }
}

@keyframes :global(slideOutToLeft) {
  0% {
    transform: translateX(0);
  }
  100% {
    transform: translateX(-100%);
  }
}
```
```css
.active {
  position: relative;
  transform: translateX(0);
  :global {
    animation: slideInFromRight 0.35s ease-in-out;
  }
}

.hidden {
  transform: translateX(-100%);
  :global {
    animation: slideOutToLeft 0.35s ease-in-out;
  }
}
```

**Comment by cansin** [comment]
@mnpenner did you figure it out?

**Comment by mnpenner** [comment]
@cansin No. I'm still using the workaround. Looks like a bug in css-modules to me.

**Comment by AlexGalays** [comment]
Still no fix or official workaround?

**Comment by piyushchauhan2011** [comment]
I think it's best to use composition here

```css
.App {
  text-align: center;
}

.logo-animation {
  animation: logo-spin infinite 20s linear;
}
@keyframes logo-spin {
  from { transform: rotate(0deg); }
  to { transform: rotate(360deg); }
}

.logo {
  composes: logo-animation;
  height: 80px;
}
```

**Comment by TrySound** [comment]
Should work here
https://github.com/css-modules/postcss-icss-keyframes

**Comment by mnpenner** [comment]
@TrySound Can this ticket be re-opened? Your plugin is nice, but it doesn't really address the heart of the problem.

We have to exclude both `@keyframes` and `animation:` blocks from the local context because one gets transformed, but not the other, which breaks the CSS.

With your new plugin, `postcss-icss-keyframes`, we *still* have to exclude both from the local context, but then the animation names can be transformed after-the-fact.

I think most of us would prefer that we could just throw *everything* including animations in a `:local` block (or enable local as the default via the CSS module settings), and simply have it work (so that we don't have to flip back and forth between `:local` and `:global`).

**Comment by mrchief** [comment]
They both get transformed correctly if enclosed in the same block. E.g., this works:

```css

.module {
  .logo-animation {
    animation: logo-spin infinite 20s linear;
  }
  @keyframes logo-spin {
    from { transform: rotate(0deg); }
    to { transform: rotate(360deg); }
  }
}
```

**Comment by mnpenner** [comment]
@mrchief What do you mean by "the same block"? Do you mean the same file? Because your `@keyframes` is not inside `.logo-animation`.

I just tried updating every package I think might be relevant,

```
├─ autoprefixer@6.5.1
├─ css-loader@0.28.5
├─ icss-utils@2.1.0
├─ less-loader@4.0.5
├─ less-plugin-autoprefix@1.5.1
├─ less@2.7.2
└─ postcss-loader@2.0.6
```

I threw this in one of my .less files:

```less
:local {
    .wrap {
        animation: logo-spin infinite 20s linear;
    }

    @keyframes logo-spin {
        from { transform: rotate(0deg); }
        to { transform: rotate(360deg); }
    }
}
```

And the output I get is:

```css
.AddStopButton_wrap--FoJr- {
    -webkit-animation: AddStopButton_logo-spin--1tzsL infinite 20s linear;
    animation: AddStopButton_logo-spin--1tzsL infinite 20s linear;
}
@-webkit-keyframes logo-spin {
    from {
        -webkit-transform: rotate(0deg);
        transform: rotate(0deg);
    }
    to {
        -webkit-transform: rotate(360deg);
        transform: rotate(360deg);
    }
}
@keyframes logo-spin {
    from {
        -webkit-transform: rotate(0deg);
        transform: rotate(0deg);
    }
    to {
        -webkit-transform: rotate(360deg);
        transform: rotate(360deg);
    }
}
```

As you can see, the `@keyframes` name and animation name still don't match up. Looks broken to me.

**Comment by mrchief** [comment]
Yeah I mean same file. But your setup is different as it uses less. I use postcss with [cssnext](https://github.com/MoOx/postcss-cssnext) (cssnext has bunch of plugins bundled up within).

This is what I get (other css props omitted for brevity):

```css
.submitButton {
  .spin-container {
   ...

    .spinner {
      ...
      animation: rotate 0.8s infinite linear;
      ...
    }
  }
}

@keyframes rotate {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
```

**output**

```css
...
.styles__submitButton-1TYvP .styles__spin-container-1zk-6 .styles__spinner-1LN5V {
     ... 
      -webkit-animation: styles__rotate-1K2Xu 0.8s infinite linear;
              animation: styles__rotate-1K2Xu 0.8s infinite linear;
     ....
    }

@-webkit-keyframes styles__rotate-1K2Xu {
  0% { -webkit-transform: rotate(0deg); transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); transform: rotate(360deg); }
}

@keyframes styles__rotate-1K2Xu {
  0% { -webkit-transform: rotate(0deg); transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); transform: rotate(360deg); }
}
```

**webpack**

```js
{
  test: /\.css$/,
  exclude: /node_modules/,
  loader: ExtractTextPlugin.extract({
    fallback: 'style',
    use: [
      {
        loader: 'css',
        options: {
          importLoaders: 1,
          sourceMap: true,
          modules: true,
          context: path.join(process.cwd(), './src'),
          localIdentName: isDev ? '[name]__[local].[hash:base64:5]' : '[hash:base64:5]',
          minimize: !isDev
        }
      },
      {
        loader: 'postcss'
      }
    ]
  })
}
```

**postcss.config.js**

```js
module.exports = (ctx) => ({
    sourceMap: true,
    plugins: [
      require('postcss-import')(),
      require('postcss-url')(),
      require('postcss-nested')(),
      require('postcss-cssnext')({
        browsers: ['ie >= 10', 'last 2 versions'],
        warnForDuplicates: false
      }),
      require('postcss-browser-reporter')(),
      require('postcss-reporter')()
    ],
  }
);
```

**Comment by Download** [comment]
Seen a bunch of issues related to this and the longhand trick has been recommended elsewhere too. It really seems to work. It works for my scenario as well.

**Comment by westtrade** [comment]
> Using longhand animation syntax (eg. animation-name, etc) fixed my particular issue.

Doesn't work, maybe with stylus-loader

**Comment by sergeyshmakov** [comment]
Its normal behavior to apply `localIdentName` to `@keyframes` and `animation` inside because `@keyframes` may be overrriden by some other module.

For some reasons developers of css-loader dont want to fix link between `@keyframes` and `animation` inside one module styles when `:local { ... }` not being writen by you.

I my case the app is depends from vendor package with style that I cant change and I fix this issue by using `postcss-modules-local-by-default` plugin.

**Comment by allan852** [comment]
animation: frames-name .6s ease; // ok
animation: .6s ease frames-name; // not work

**Comment by brendanfalkowski** [comment]
For reference, I found this issue while debugging and documented several approaches here: https://gravitydept.com/blog/keyframe-animations-in-css-modules

**Comment by dmwin72015** [comment]
> like my code, you can solve the problem.
> 
> ```css
> @keyframes :global(slideInFromRight) {
>   0% {
>     transform: translateX(100%);
>   }
>   100% {
>     transform: translateX(0);
>   }
> }
> 
> @keyframes :global(slideOutToLeft) {
>   0% {
>     transform: translateX(0);
>   }
>   100% {
>     transform: translateX(-100%);
>   }
> }
> ```
> 
> ```css
> .active {
>   position: relative;
>   transform: translateX(0);
>   :global {
>     animation: slideInFromRight 0.35s ease-in-out;
>   }
> }
> 
> .hidden {
>   transform: translateX(-100%);
>   :global {
>     animation: slideOutToLeft 0.35s ease-in-out;
>   }
> }
> ```

not work, Expected @keyframes identifier

**Comment by rustho** [comment]
+1

**Comment by nixolas1** [comment]
`
.myClass {
  color: black;
  & :global { animation: scrollAnim 3s infinite ease-in-out }
}
`
 worked for me, in a css module file, with 
`
@keyframes :global(scrollAnim) {
  0% { transform: scaleX(0) }
  100% { transform: scaleX(1) }
}`

in a separate, non-module css file

**Comment by matias4205** [comment]
For those not using pure css, you have to do something like this:

```css
/* styles.module.css */
.myClass {
  /* some other local css */
}

.myClass:global {
  animation-duration: .3s;
  animation-fill-mode: forwards;
  animation-name: fadeInUp;
}
```
```css
/* styles.global.css */
@keyframes fadeInUp {
  from {
    opacity: 0;
    transform: translateY(35px);
  }

  to {
    opacity: 1;
    transform: translateY(0);
  }
}
```
