### ISSUE TITLE
[Question] Recommended approach for working with embeddable widgets

### ISSUE THREAD

**Issue by elado** [css-modules/css-modules#144]
I'm working on an embeddable widget with a bunch of components. css-modules produces essentially a single unique class per rule, and this doesn't prevent from containing page to override styles, due to lack of specificity.

So for example:

``` scss
// MyMidget.css
.header { color: red }
```

``` jsx
// MyMidget.jsx
<header className={styles.header}>...</header>
```

will result in

``` html
<header class="MyWidget_header_[hash]">...</header>
```

but any rule in the containing page like

``` css
body.theme-blue header { color: blue; }
```

would override my class.

Is there a recommended approach here?

Before css-modules I'd just create everything nested and divided into files with scss:

``` scss
// MyWidget.css
.MyWidget {
  @import "./header";
}

// header.css
.header { color: red; }
```

(not bulletproof, but increases specificity).

**Comment by themitchy** [comment]
Seems to me that a theme _should_ override default styles (isn't that what a theme **is**?)

If you really do want to flip that pattern around and make your widgets' styles non-overridable you may want to consider inline styles for those.

**Comment by elado** [comment]
@themitchy the word `theme` was misleading. It's the site's own theme but this can be a better example:

```css
body.desktop header { color: blue; font-size: 2em; }
```

The flat CSS structure makes it easy to override with any better-specificity rule.

I ended up going back to nested `scss` as described in the initial comment.

**Comment by mattywong** [comment]
Might be a bit late, but recently have undertaken a similar embedded widget project using CSSModules and ran in to something similar, except ours was the opposite, we wanted to inherit the pages styles.

If you haven't already, checkout [Third Party Javascript](http://thirdpartyjs.com/). There's a couple ways they mentioned if you're trying to avoid the parent page specificity.

1. Inline Styles. Though can still be overridden by !important, which leads to...
2. Abuse !important. Has the highest specificity, though obviously comes with it's own caveats. However if using class composition as CSSModules recommends and a well structured style architecture, the chance of conflicting styles can be contained quite minimally.
3. Embed your widget in an iFrame. If you're really concerned about publishers overriding your styles, iFrames are probably the way to go as it's all isolated.

**Comment by elado** [comment]
@mattywong thanks.
I ended up writing a SASS BEM mixins that generate higher-specificity selectors using `.classname[class]`, and resetting styles for `.classname *`.

See here:
https://gist.github.com/elado/af17ed255333dc34375876a4decd827e


```css
.ns-InfoPane, .ns-InfoPane * { /* reset stuff like margin: 0; padding: 0; ... */  }
.ns-InfoPane[class] { border: 1px solid red; }
.ns-InfoPane[class] .ns-InfoPane__header { background: gray; }
...
```
