### ISSUE TITLE
pseudos with global rules

### ISSUE THREAD

**Issue by rossPatton** [css-modules/css-modules#148]
i have a case that i believe to be pretty common, that I can't figure out how to do with css modules

I've seen the other issues documenting pseudo selectors and composes, that's not a problem

The problem is when I want to export a global css class, with a `:focus` pseudo selector

```css
// content only visible to screen readers
.visuallyHiddenExceptOnFocus {
  border: 0;
  clip: rect(0 0 0 0);
  height: 1px;
  margin: -1px;
  overflow: hidden;
  padding: 0;
  position: absolute;
  width: 1px;
}

// or if tabbing through the document
.visuallyHiddenExceptOnFocus:focus {
  background: #fff;
  clip: auto;
  display: block;
  height: auto;
  margin: 0;
  overflow: visible;
  position: static;
  width: auto;
}

// what I want to be able to do
:global(.visuallyHidden) {
  composes: visuallyHiddenExceptOnFocus;
}
```

I've tried numerous variations of the above, including wrapping `visuallyHiddenExceptOnFocus` with `:local()`, and nothing works. It seems to me that a lot of sites have helper classes like this that are used all throughout the site, shouldn't this kind of case be supported?

Thanks
