### ISSUE TITLE
Support for partial global selectors

### ISSUE THREAD

**Issue by MrBlenny** [css-modules/css-modules#162]
There are occasions where we do not have access to the imported css module and want to change appearance by adding a simple class such as `active` (not prefaced with anything).

Here is a react/jsx example (in this example we do have access to the css module but there are of course times where we don't):

``` jsx
import styles from './TabStyles.css'

<div className={styles.tabs} >
    <a className="active">Tab 1</a>
    <a>Tab 2</a>
    <a>Tab 3</a>
</div>
```

How does one create appropriate css for this scenario? What I am after is something like this:
``` css
.tabs > a{
    padding: 15px;
    border-bottom: 1px solid black;
}
.tabs > a.active:global{
    border-bottom: 1px solid green;
}
```

Is there some sort of equivalent syntax?
