### ISSUE TITLE
Using # instead of . for local names

### ISSUE THREAD

**Issue by alexkg** [css-modules/css-modules#163]
Howdy, wasn't sure where to ask, but...

Is there a way to let class names be class names, performing the name mangling operation on `#selectors` instead? For example:

```css
#foo.bar { float:left; }
```

Would become:
```css
.foo-1fjxwai89pq.bar { float:left; }
```

Where in the code would I look to make a change like this?

Thanks!

**Comment by geelen** [comment]
If you want a real class name `.bar`, you can use the `:global` directive:

```css
.foo:global(.bar) { float: left; }
```

So there should be no need to involve `#`, I hope!
