### ISSUE TITLE
manual or automatic definition of :export'ed value type

### ISSUE THREAD

**Issue by brumm** [css-modules/css-modules#165]
Currently, values `:export`ed from css end up being imported as strings inside javascript.
It'd be nice to have either automatic and/or manual control over the type of the exported value.

```
:export {
  myValue: 1.35, 'float';
}
```

Additionally, a way to deal with stripping any existing units would be great. For now, this scss function works well though. (Excerpt from some of my code):

```scss
$poster-width: 240px;
$poster-ratio: 1.5;

@function strip-units($value) {
  @return $value / ($value * 0 + 1);
}

:export {
  posterWidth: strip-units($poster-width);
  posterRatio: $poster-ratio;
}
```
