### ISSUE TITLE
How to get married to EQCSS?

### ISSUE THREAD

**Issue by ctaepper** [css-modules/css-modules#169]
https://github.com/eqcss/eqcss adds the possibility for container queries instead of media queries (imho this will get very big in the future). However the syntax is not compatible with css modules as far as i can see.

```css
/* give .myDiv a red background if at it is at least 300px wide */
@element ".myDiv" and (min-width: 300px) {
  .myDiv {
    background: red;
  }
}
```

The first ".myDiv" in the @element tag does not get picked up by css modules and is not transformed into a local classname. This would by an awesome edition to css modules. Is that in any way possible?

**Comment by dvkndn** [comment]
Hi @ctaepper, you can save the hashed classes (by CSS Modules) and use it later if you want. For example:

```css
/* my-styles.css &/
.myDiv { color: red; }
```

```js
// index.js maybe, or any file in your build process
import styles from 'my-styles.css';
window.STYLES = styles;
```

```js
// in your script tag
const myDivClassName = window.STYLES.myDiv;
// now you have a string which is "myDiv" class, locally hashed by CSS Module previously
```

Please note that: EQCSS is a JS plugin, it runs in browser, at run-time. CSS Modules is a part of the build process. They are 2 different enviroments/processes. Maybe someone can think of a better way to communicate between them, but for now my only way is to save to a global variable (which I think is not really good)

**Comment by ctaepper** [comment]
i am not sure how this helps me in any way? my code example is inside a css file. css modules is hashing the `myDiv` of the class selector, but not at `@element ".myDiv"`.

**Comment by dvkndn** [comment]
Hi @ctaepper, I don't think CSS Modules can hash `@element ".myDiv"`, because it is defined in a script tag (CSS Modules's "hashing" progress happens when you import a CSS file, by CSS loader for example).

Therefore, instead of hashing `@element ".myDiv"`, you can use the hashed class name in your EQCSS, something like `@element styles.myDiv`, in which `styles.myDiv` is a string returned by CSS Modules of `myDiv` class, like `myDiv_h38hs`

**Comment by sunny-g** [comment]
@dvkndn `@element .myDiv` is defined in the CSS file. The reference to `.myDiv` below this line is also in the same CSS file and is being hashed, but not the first reference. He wants this:
```css
@element ".myDiv" and (min-width: 300px) {  /* with or without quotes, whatever works */
  .myDiv {
    background: red;
  }
}
```

to become this:
```css
@element .myDiv___3kd4u and (min-width: 300px) {  /* with or without quotes, whatever works */
  .myDiv___3kd4u {
    background: red;
  }
}
```

Does that make sense? Is there any obvious reason why the second reference is being picked up, but not the first?
