### ISSUE TITLE
Idea: quarantine mode

### ISSUE THREAD

**Issue by geelen** [css-modules/css-modules#17]
This is for @markdalgleish after chatting last night

You said something like "any CSS file should be able to be treated as local" by not allowing any global selectors to leak out, or translating all `h1`s to `.tag__h1` like in your demo. And then we talked about globals in terms of dead-code elimination. And we've argued about whether globals should just fall through using `local-by-default`. For the record, here's where we are right now:

``` css
/* this falls through, but we want to raise a warning in the linter */
body {
  background: papayawhip;
}

/* this is how you are supposed to be doing globals */
:global(h1) {
  font-size: 900px;
}

/* this should maaaaaaybe throw a warning? */
.header a {
  color: peru;
}

/* this should probably not throw a warning cause it's not really leaking a global */
.footer > a {
  color: palegoldenrod;
}
```

But let's consider someone _else's_ code, like bootstrap. It starts with normalise, then sets default styles on a bunch of bare tags. Which makes it easy to get started with, but breaks the whole isolation idea we're talking about. So here's something I just thought of:

``` css
:global(h1) {
  composes: global(h1) from "bootstrap.css";
}
```

So, `composes` doesn't make any sense for a global, since it normally just exports multiple class names. But, if we were doing dead-code elimination, this could be an instruction to say **don't delete rules about h1 in bootstrap.css**.

So then we'd need a way to say **don't delete _any_ of file X**, but maybe that could just be done with:

``` css
@import "reset.css";
```

or in JS

``` js
import styles from "reset.css";
styles.acceptAllGlobals();
```

Anyway, it's all churning around in my head so I wanted to try to write it down. But basically, if you `compose` someone elses CSS, it would be badass to be able to guarantee you were _only_ getting the styles you were asking for.

**Comment by joshwnj** [comment]
Great ideas, I think I agree with everything going on here :) Recapping my thoughts from the earlier discussion:

- the way I understand it, there are 2 use-cases that should probably be handled differently. One is when you want to import global selectors as local (eg. if you want the `h1` from bootstrap), the other is if you want to import global and keep them global (like `reset.css`).

- I like the look of `composes: global(h1) from "bootstrap.css";` for the first case. If the `h1` is imported as  `.tag__h1___bootstrap__whatev` like in @markdalgleish 's demo, it feels obvious to the dev that only the selected things are imported and not all of bootstrap.

- I like `@import` for "importing global as global", since that's what `@import` has always meant so we're not introducing anything new.

Let me know if I'm on the same page as others

**Comment by geelen** [comment]
Yeah, I just realised that my `h1` example isn't great. It only works if the tag you're exporting is the same as the tag you're composing.

```css
:global(p) {
  composes: h4 from "bootstrap.css";
}
```

Makes no sense. We'd have to go in and copy the `h4` styles from Bootstrap somewhere and rename them to `p`. That's the sort of thing something like Sass could do, but it's not really appropriate for CSS Modules.

I think it'd be better to focus on being able to style things (like every `p` tag) without needing global CSS.

Still, the second use-case you mention is pretty great. Taking a global `h1 {}` and importing it just on the elements you want, is pretty boss.
