### ISSUE TITLE
Question: Making css-module work with post-css

### ISSUE THREAD

**Issue by renarsvilnis** [css-modules/css-modules#172]
Hi,
starting a new project and really I want to use css-modules for it. (_Note: 2nd attempt at switching from sass to css-modules_)
As before setting up the basics to make css-modules work is easy. But once I start get past hello-world into doing some real-world stuff css-modules starts getting frustrating.

**I'm currently stuck on making math calculation in variables work.**
I completely understand that css-modules role is not deal with math operations. As I use post-css in my webpack build and i'm familiar with post-css ecosystem, tried adding [`postcss-math`](https://github.com/shauns/postcss-math) which adds `resolve` (_seen in code examples belove_). But the issues is that css-module parsing happens after post-css and any `resolve` calls in variable declarations `@value` are just ignored and is outputed as `line-height: resolve(baseFontSize * 1,5em)`

I tried looking at [`react-boilerplate`](https://github.com/mxstbr/react-boilerplate/blob/master/internals/webpack/webpack.base.babel.js#L74:L82) for inspiration on how to be able to do it. But wasn't able to find anything that would help.

**Wondering what are other people workflow for this?**
**Do you still just parse through SASS before css-modules?**
**Are there any other post-css modules I should be aware of?** https://github.com/css-modules/css-modules/issues/92#issuecomment-223745698

```css
@value baseFontSize: 18px;
@value lineHeight: resolve(baseFontSize * 1,5em);

@value h1FontSize: resolve(48 / 16rem);
@value h1LineHeight resolve(48 / 18rem);

// ...

.h1 {
  font-size: h1FontSize;
  line-height: h1LineHeight;
}
```

**Comment by dvkndn** [comment]
Hi @renarsvilnis :D I think I can help you, since I use CSS Modules, PostCSS, and do math in our production CSS.

I can't sure unless I see your config(s), but I guess the issue here is not related to CSS Modules, but PostCSS alone. Please try to turn off CSS Modules and confirm if your issue (`resolve` not work) is still existed?

Please note that CSS Modules has nothing to do with PostCSS. If you are using Webpack, you will see there are loaders, and you should think of these loaders as a pipeline: your css will go through those loaders, one by one, and each loader will transform your css, without knowing about other loaders.

So, in your case, the flow should be like this: first, your css goes through post-css loaders, or to be exact, through your post-css plugins, one by one. One of these plugins will do the calculation and variables stuff. After going through all plugins, **your css should have all math formula and variables resolved**. Now, CSS Modules does its job, and don't care anything about post css

**Comment by dvkndn** [comment]
@renarsvilnis for example, this is how we use CSS Modules, postcss with postcss-calc (for math calculation): https://github.com/QuoineFinancial/exchange/

Files to note:

https://github.com/QuoineFinancial/exchange/blob/master/cfg/defaults.js#L19
- this is our webpack loaders for css files.
- post-css loader run first, then css loader (which has CSS Modules as option)
- on line 22, note the `importLoaders` option, this mean post-css loader also applied when we continue import css from css

https://github.com/QuoineFinancial/exchange/blob/master/cfg/base.js#L50
- this is our post-css plugins, you can see postcss-calc (for math resolve) here, which will be run after postcss-simple-vars (for variable resolve)

**Comment by renarsvilnis** [comment]
@dvkndn I know it's completely that my issue is not related with CSS Modules itself.
I'm just asking for advice/guides/workflows for what is might be needed for an SASS user to migrate to CSS-Modules and have similar sass like features, such as math operations in variables.

I just though that asking it here might yield the best results as contributors might already have had similar experience I'm going through.

-----

Tried adding postcss plugins you are using in `QuoineFinancial`. 
Now using `postcss-simple-vars` + `postcss-calc` allows me to do calculations in variables. Now I must use `$myVariable: value` syntax to declare variables, same as SCSS, which does math operations, but naturally `css-modules` doesn't make them as exports as they must be declared as `@value myVariable: value`.

Below have tried multiple approaches. 2nd one works for local variables, but can't be exported and used in other `css/js` files.

```scss
// 1. doesn't work
@value h1FontSize: calc(48 / 16rem);
.h1 { font-size: h1FontSize; } // Output: font-size: calc(48 / 16rem);

// 2. works, but $h1FontSize not exported by css-modules
$h1FontSize calc(48 / 16rem);
.h1 { font-size: $h1FontSize; } // Output: font-size: 3rem;

// 3. doesn't work
$h1FontSize calc(48 / 16rem);
@value h1FontSize: $h1FontSize;
.h1 { font-size: h1FontSize; } // Output: font-size: calc(48 / 16rem);
```

**Comment by dvkndn** [comment]
Hi @renarsvilnis , for import and export variables across files, you can use [postcss-import](https://github.com/postcss/postcss-import) plugin. For example:

1. Require that plugin at the begining of your postcss:
https://github.com/QuoineFinancial/exchange/blob/master/cfg/base.js#L44

2. Declare your variables:
https://github.com/QuoineFinancial/exchange/blob/master/src/styles/variables/size.css
(in the example above, I use postcss-simple-vars to declare variables, but you can use whatever you want)

3. Use your variables from other files (note the `@import`, not `import`. We are importing files with postcss, not webpack/css-loader):
https://github.com/QuoineFinancial/exchange/blob/master/src/styles/base/padding.css#L1

**Comment by dvkndn** [comment]
There is one more thing I'd like to clarify:

If you are using https://github.com/css-modules/postcss-modules-values for your variables system, you can't do math with them, or to be exact: you can't use postcss plugin with them. `@values` is processed by CSS Modules, which is a part of CSS Loader, which is runned **after** PostCSS Loader, which has the calculation plugin

So, if you want to do math using PostCSS plugin with variables, then those variables must be defined using a PostCSS plugin too, so all those things happen inside the phase of PostCSS loader.

**Comment by renarsvilnis** [comment]
@dvkndn Thanks a lot for helping -  [`postcss-modules-values`](https://github.com/css-modules/postcss-modules-values) + `postcss-calc` works perfect.

```scss
@value h1FontSize: calc(48 / 16rem);

.h1 {
  font-size: $h1FontSize; // Output: 3em;
}

```
