### ISSUE TITLE
other implementation of css module instead of using js object

### ISSUE THREAD

**Issue by craigcosmo** [css-modules/css-modules#178]
Hi css-modules team, 

Thanks for making this. What I see about this plugin is it replaces the name of CSS class in .jsx and .css or .scss file with a hash string. If it's that's all it does why don't we just do like this.

home.scss

``` scss
.home {
    width:500px;
}
.box {
   width:200px;
}
```

Home.jsx component

``` jsx
render(){
   <div className="home">
       <div className="box"></div>
   <div>
}
```

That is our base code. Now css-module will make that become this

home.scss

``` scss
.home_1fg8e {
    width:500px;
}
.box_78uuy {
   width:200px;
}
```

``` jsx
render(){
   <div className="home_1fg8e">
       <div className="box_78uuy"></div>
   <div>
}
```

Isn't that more natural?
