### ISSUE TITLE
Redundant Styles in the DOM

### ISSUE THREAD

**Issue by vizFlux** [css-modules/css-modules#180]
Anybody has any idea of what leads to this kind of redundancy?

<img width="346" alt="screen shot 2016-10-21 at 10 50 13 am" src="https://cloud.githubusercontent.com/assets/13939164/19585143/a000b738-977c-11e6-862a-693cfaeaa3d7.png">

As shown in the picture, there's so much of redundant styles being injected to the same element.

it is a MERN, react project.

an example how styles are being imported in the project is as the following:

``` css
@import "../../../App/style/css/settings/settings.css";
@import "../../../App/style/css/elements/elements.css";
@import "../../../App/style/css/components/components.css";

.heroWrap {
  position: relative;
  min-height: 550px;
  background-image: url('../../../../assets/images/hero-bg.jpg');
  background-position: bottom;
  background-size: cover;
  background-repeat: no-repeat;
  composes: container-fluid;
}

.heroPanel {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 550px;
  composes: wrap-lg;
}

.heroHeader {
  composes: ep-heading-hero;
  color: var(--clr-white);
}
```
