### ISSUE TITLE
Is there a tool for discovering similar classes and merging them automatically?

### ISSUE THREAD

**Issue by mohsen1** [css-modules/css-modules#181]
I'm researching to see if anyone has done this before I start doing it myself. 

Idea is simple, if you have two or more classes that share properties, we automatically change the CSS Modules code to have common class names that can be replaced with the original class names.

Example:

```css
.class1 {
    background: red;
    margin-top: 10px;
}
.class2 {
    background: red;
    margin-top: 10px;
    margin-left: 10px;
}
```

Result (CSS)
```css
.class1{
    background: red;
    margin-top: 10px;
}

.class1---class2 {
    margin-left: 10px;
}
```

Result (in JS)

```js
  import style from './style';

  console.log(style.class1) // => "class1"
  console.log(style.class2) // => "class1 class1---class2"
```

Obviously this kind of optimization can have negative impact on one side (JS or HTML size vs CSS size) but in a real application with tons for CSS or HTML it makes sense to pick one side.
