### ISSUE TITLE
best practice composing an angular component

### ISSUE THREAD

**Issue by ctaepper** [css-modules/css-modules#183]
With angular 1.5, the component() method was introduced in favour of directive(). So now i create a `my-component` which has for demo's sake the template `<h1>hello world</h1>`

i can use css modules to define/compose classes for that h1, again for demo's sake i want to use the @tachyons library. so my code looks like this

``` css
/* styles.css */
.title {
  composes: f2 from 'tachyons'
}
```

``` js
// module.js
import css from './styles.css'
export default {
  template: `<h1 class="${css.title}">hello world</h1>`
}
```

however, the resulting html will be

``` html
<my-component>
   <h1 class="some__localclass__title">hello world</h1>
</my-component>
```

I don't see any way of styling the root tag of the component? of course, i can always do something like 

``` css
my-component {
  display: block;
}
```

however, i cannot compose inside a none local classname. so what i am doing right now as a workaround that uses the $onInit of the controller to add a class to the root element of the component

``` css
/* styles.css */
.component {
  composes: db from 'tachyons'
}
.title {
  composes: f2 from 'tachyons'
}
```

``` js
// module.js
import css from './styles.css'
export default {
  controller: class {
    constructor($element) {
      this.$element = $element
    }
    $onInit() {
      $this.$element.addClass(css.component)
    }
  }
  template: `<h1 class="${css.title}">hello world</h1>`
}
```

But this just doesn't feel right... anyone has a better way to do this?
