### ISSUE TITLE
Optimizing css selector to properties relation

### ISSUE THREAD

**Issue by vojtatranta** [css-modules/css-modules#193]
Has anyone thought about optimizing the way how css are "translated" into class names?

For example, if I have lots of declarations that share some property:
```css
.some-class {
  font-weight: bold,
}

.other-class {
  width: 300px;
  font-weight: bold;
}

.text-class {
  font-weight: bold;
  text-decoration: underline;
}
```

This could be obviously translated into this:
```css
.bold-font {
  font-weight: bold;
}

.other-class {
  width: 300px;
}

.text-class {
  text-decoration: underline;
}
```

and used as:
```html
<div class="bold-font other-class"></div>
<span class="bold-font text-class"></span>

```

I know that it seems as small optimization, but when we imagine large stylesheets, it could save few kilobytes, even more when combined with some selector shortening.

What do you think?

**Comment by vojtatranta** [comment]
So I started a research, and the result is... Well, surprising!

I had `124kB` css and I squeezed it into `70kB` with code I wrote in an hour please check it here: https://github.com/vojtatranta/css-property-selector-optimization

Any ideas or thoughts, whether it makes sense?

**Comment by joeybaker** [comment]
That's huge! Nice work!

**Comment by dvkndn** [comment]
This is of useful. In our case, this is actually what we start at first. We have some "base" styles that are just 1 property, in seperate file, like this:

```css
/* color.css */
.red { color: red; }
```

Then we use compose **everywhere** else

```css
/* button.css */
.main { compose: red from "base/color.css"; }
```

It might sound weird, but I found that this approach is good for us:
- all base styles never changed once written, which is easy to maintaince and scale and share between our apps
- all component styles use `compose`, to make sure everything follow a style guide

**Comment by tivac** [comment]
Similar-but-not-identical to the ID posited in #181 - cool to see some results and code, definitely interested in trying it out!

**Comment by vojtatranta** [comment]
Of course it would raise html/js size, but we could optimize easily even selector names:
```html
<div class="bf oc"></div>
<span class="fb tc"></span>
```

So html would not grew too much.

**Comment by taion** [comment]
This accomplishes close to the same thing as the standard ruleset merge optimization, though: https://github.com/ben-eb/postcss-merge-rules

Does this add much value on top of that?

**Comment by tivac** [comment]
@taion I ran `postcss-merge-rules` against the CSS generated by [crucible](https://github.com/tivac/crucible)

It didn't do much, shaved off about 1k from a 150k file.

https://gist.github.com/tivac/35df917ba9d9fe2a90e6f4c4c03e6eb3

**Comment by taion** [comment]
Interesting – I wonder why that optimization is so ineffective. Maybe it needs to be combined with selector minification to avoid bloat from repeating the selectors.

**Comment by vojtatranta** [comment]
@taion I will examine it

**Comment by vojtatranta** [comment]
@taion and it might be ineffective, because it is difficult to find selectors that "match" the way then are not filled enough with properties, so they can be merged with other selectors.

This is the reason why creating new selectors might be helpful.

**Comment by vojtatranta** [comment]
Oh, it seems this idea is duplicate of this project: http://css.github.io/csso/csso.html

**Comment by taion** [comment]
It's the same idea – it's a common optimization. The PostCSS plugin also handles partial merging: https://github.com/ben-eb/postcss-merge-rules#by-partial-declarations

Where I expect this merge approach not to be as helpful is if selector names are long – but that should be a non-issue with CSS modules, no?

**Comment by vojtatranta** [comment]
@taion I taking only css modules into count, because in order to make such optimization, you also need modify selectors in the "HTML" / JS.

**Comment by vojtatranta** [comment]
@taion I took a look - this is also not the same thing. Because this does not create new selectors that break current CSS. My approach would do that. 

But I think it would be super-awesome to combine my way (creating of selector per repeated rule) and partial merging. It might be possible to compress CSS by more than 50%.

**Comment by taion** [comment]
It nets out, right? Ignoring the weight of whitespace for now, in your initial example, suppose we shorten the class names. Starting with:

```css
.a {
  font-weight: bold,
}

.b {
  width: 300px;
  font-weight: bold;
}

.c {
  font-weight: bold;
  text-decoration: underline;
}
```

We can generate either

```css
.a {
  font-weight: bold,
}

.b {
  width: 300px;
}

.c {
  text-decoration: underline;
}

:export {
  a: a;
  b: a b;
  c: a c;
}
```

Or

```css
.a, .b, .c {
  font-weight: bold,
}

.b {
  width: 300px;
}

.c {
  text-decoration: underline;
}

:export {
  a: a;
  b: b;
  c: c;
}
```

It ends up being virtually the same.

**Comment by vojtatranta** [comment]
@taion aha, see your point, you are right, it is virtually the same. I have to try it out, how much it can compress css.

**Comment by taion** [comment]
Sure – don't forget the cost of the longer selectors, though. You'll get less CSS if you don't repeat the selectors in your CSS, but you end up repeating them in the mappings in your JS, so it nets out.

**Comment by vojtatranta** [comment]
@taion yeah, but still `font-weight: bold;` is much longer then just `fsb`.

**Comment by vojtatranta** [comment]
@taion I tried out `postcss-merge-rules` and I am not satisfied. I put there `124kB` css and got no optimization, which is nonsense I think.

So I assume it works without creating new selectors, look:
```css
.modal--variable {
    width: auto;
    height: 20px;
    font-weight: 300;
}

.modal-tab__content--stretched {
    height: 20px;
    width: auto;
    font-weight: bold;
}
```
with `postcss -u postcss-merge-rules`:
```css
.modal--variable {
    width: auto;
    height: 20px;
    font-weight: 300;
}

.modal-tab__content--stretched {
    height: 20px;
    width: auto;
    font-weight: bold;
}
```

No difference at all.
