### ISSUE TITLE
How to work with CSSNext?

### ISSUE THREAD

**Issue by Shyam-Chen** [css-modules/css-modules#196]
OK
```css
:global .mdl-grid--center {
  justify-content: center;
}

:global .mdl-cell--center {
  text-align: center;
}

:global .mdl-cell--right {
  text-align: right;
}
```
***
Not working
```css
:global {
  & .mdl-grid--center {
    justify-content: center;
  }

  & .mdl-cell--center {
    text-align: center;
  }

  & .mdl-cell--right {
    text-align: right;
  }
}
```
