### ISSUE TITLE
Using 'composes' in nested class

### ISSUE THREAD

**Issue by rpunkfu** [css-modules/css-modules#202]
Hi!

I was wondering if there's any way to do composition in a nested class like this:

```css
.foo {
  & .bar {
    composes: baz from '...';
    font-size: 14px;
  }
}
```

instead of this:

```css
.foo {
  & .bar {
    font-size: 14px;
  }
}

.bar {
  composes: baz from '...';
}
```

It's really annoying that I have to separate `composes` from other styles. I was wondering if this is by-design or just a bug?

**Comment by maciejtatol** [comment]
Yup, sounds great 👍

**Comment by TheSisb** [comment]
1- What doesn't work / what's the error message with the first code sample?  I believe it should work correctly.
2- What does your build look like (webpack config)?
2- Your two code samples give different results.  In the first example, `.bar` gets `.baz`'s styling only within `.foo`.  In the second example, `.bar` always gets `.baz`'s styling.  Are you sure you're testing your issue correctly?

**Comment by rpunkfu** [comment]
Hi :)

1. `Error: composition is only allowed when selector is single :local class name not in ":local(foo) :local(bar)"`

2. 
```js
 {
        test: /\.css$/,
        loaders: [
          'style?sourceMap',
          'css?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]&camelCase',
          'postcss',
        ],
      },
```

3. Yes, I know how this example _should_ behave, that's what annoys me, I want to compose _only_ inside of `.foo`, right now I need to compose _all_ of the `.bar`s and then have some specific styles for it inside of `.foo .bar` :(

**Comment by ghost23** [comment]
I get a similar error message when I attempt to do something like this:

```
input[type="text"] {

  &.success {
    composes: successBorder;
  }
  ...
}
```

`Error: composition is only allowed when selector is single :local class name not in "input[type="text"]:local(.success)"`

I assume, this is roughly the same issue, right?!

**Comment by rpunkfu** [comment]
Hi @ghost23, yup, this is the same issue ;)

**Comment by rpunkfu** [comment]
@TheSisb any update on this? :)

**Comment by TheSisb** [comment]
The way composes works is by concatenating class names so

```css
.a {
  color: red;
}
.b {
  composes: a;
}
```

Outputs
```html
<div className="a b" />
```

Therefore I don't see how a nested class can compose.

```css
.a {
   .c {
     composes: b;
   }
}
```

Adds complexity because now you're using CSS Cascade.

It's like saying
```html
<div class="a">
  <div class="c">  // This should be class="b c" in this case, but the simple css modules compose transform is unaware of the dom position of this div
</div>

<div class="f">
  <div class="c"> // But not here!
</div>
```

Hope that helps.
