### ISSUE TITLE
:global nested

### ISSUE THREAD

**Issue by AlexanderTserkovniy** [css-modules/css-modules#210]
Hi guys,

Correct me if I am wrong, but I did not find any similar issue created here.

How could I achieve this:

```css
.css-module-class .nested-raw-class {
  color: blue;
}
```

To have output looks like this:
```css
.crazy-long-css-module-selector-which-have-initial-css-module-class .nested-raw-class {
  color: blue;
}
```

Notice that `nested-raw-class` remained untouched.

Thanks.
