### ISSUE TITLE
Composition ? what's the result of css after it executed ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [css-modules/css-modules#218]
```
.className {
  color: green;
  background: red;
}

.otherClassName {
  composes: className;
  color: yellow;
}
``` 
??? `===` ???

```
.otherClassName {
  color: green;
  background: red;
  color: yellow;
}
```

**Comment by tivac** [comment]
http://m-css.com/#!/?state=W3sibmFtZSI6IjEuY3NzIiwiY3NzIjoiLmNsYXNzTmFtZSB7XG4gIGNvbG9yOiBncmVlbjtcbiAgYmFja2dyb3VuZDogcmVkO1xufVxuXG4ub3RoZXJDbGFzc05hbWUge1xuICBjb21wb3NlczogY2xhc3NOYW1lO1xuICBjb2xvcjogeWVsbG93O1xufSJ9XQ%3D%3D

`composes` doesn't actually combine rules that way. When used the output will be `className otherClassName`, and the last definition wins so the color will be `yellow`.

**Comment by xgqfrms-GitHub** [comment]
# it's in this way?

??? `===` ???

```
.className .otherClassName {
  background: red;
  color: yellow;
}
```

**Comment by xgqfrms-GitHub** [comment]
# Anyway, thanks a lot!

https://github.com/tivac/modular-css

http://m-css.com/#!/

```css
.mceb37c9fc_className {
    color: green;
    background: red
}
.mceb37c9fc_otherClassName {
    color: yellow
}

``` 
## to be honest, I don't like this way!

I have to use two class to achive this composed style!

```html
<div class=".mceb37c9fc_className .mceb37c9fc_otherClassName">
    OOCSS
</div>
``` 
# this way look likes much better!
```html
<div class=".mceb37c9fc_className .mceb37c9fc_className-otherClassName">
    BEM 
</div>
``` 
## BEM css module
```css
.mceb37c9fc_className {
    background: red
}
.mceb37c9fc_className_otherClassName {
    color: yellow
}
```
