### ISSUE TITLE
Keyframes import proposal

### ISSUE THREAD

**Issue by TrySound** [css-modules/css-modules#236]
Importing keyframe from a file can look like this
```css
@value anim from 'path';
.foo {
  animation-name: anim;
}
```
But with `local-by-default` local name will be processed again. Simple solution for this is using global modifier
```css
@value anim from 'path';
.foo {
  animation-name: _colon_global(anim);
}
```
Which is not quite clean and obvious and here I'd replace `_colon_global` modifier name with just `global`

I'd like to suggest extended syntax, similar to `composes` and `@value`
```js
.foo {
  // single value
  animation-name: anim from 'path';
  // multiple values
  animation-name: (anim1, anim2) from 'path';
  // regular identifiers are also possible
  animation-name: anim from 'path', local-one;
}
```
Extension restricted only to `animation-name` to reduce parsing complexity of compound `animation` prop.

/cc @geelen @sullenor @michael-ciniawsky @evilebottnawi

**Comment by TrySound** [comment]
Another case is splitting keyframes in plugin with local-only mode. So this becames cleaner
```css
@keyframes a {}
@value b from 'path';
.foo {
  animation-name: a, b;
}
// becomes in local mode
@keyframes a--hash {}
.foo {
  animation-name: a--hash, b-imported;
}
// becomes in global mode
@keyframes a {}
.foo {
  animation-name: a, b-imported;
}
```
