### ISSUE TITLE
@value multiline formatting support

### ISSUE THREAD

**Issue by zyzski** [css-modules/css-modules#250]
Value declarations don't seem to work if you put comma separated values on new lines. No compilation error, the style is just missing.

`@value fontStack: -apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif;`
works fine

![screen shot 2017-06-29 at 11 56 37 am](https://user-images.githubusercontent.com/4314335/27697416-326b36b0-5cc2-11e7-8096-fcc2c79c4bf3.png)
does not render the font correctly

This issue came up after using the CSS auto formatter _Prettier_.
I originally posted this issue here: https://github.com/prettier/prettier/issues/2355#issue-239529342

Would it be possible to support this?

**Comment by TrySound** [comment]
Hi, @zyzski 
What you got in ouput?

**Comment by markalfred** [comment]
I can confirm that the same thing happens with any type of multi-line import:

color.css:
```css
@value blackish: #111;
@value offwhite: #efe;
```

component.css:
```css
@value blackish,
  offwhite from './colors.css';

body {
  color: blackish;
  background: offwhite;
}
```

expected:
```css
body {
  color: #111;
  background: #efe;
}
```

actual:
```
body {
  color: blackish;
  background: offwhite;
}
```


However, this works correctly:
```css
@value (blackish,
  offwhite) from './colors.css';
```
postcss-icss-values version 2.0.1
