### ISSUE TITLE
Pseudo classes and `composes`

### ISSUE THREAD

**Issue by coot** [css-modules/css-modules#251]
When I have two rules:

```
.error {
  color: red}
}

.error:before {
   content: "ERROR: "
   color: orange;
}
 ```

And in another file I do
```
.message {
  composes: error from "./errors.css";
}
```

The two css styles for `.error` and `.error:before` get inlined into one rule rather than a `.message` plus `.message:before`.  Is this en expected behaviour?

**Comment by TrySound** [comment]
@coot Yep. If you will go deep into implementation, you will see that composes is not another one mixins clone. It's just compositon of a fiew classes in one exported name. Composition is functional way to build efficient systems, not inheritence where everything is thrown into a one hole.

**Comment by TrySound** [comment]
Ah, you know. It's cool. Well, composes just converts
```css
.a {
  composes: b;
}
/* into */
.a {}
:export {
  a: a b
}
which is processed by css-loader internally. It's called icss
```
