### ISSUE TITLE
Composition is only allowed when selector is single :local class name

### ISSUE THREAD

**Issue by 0x80** [css-modules/css-modules#261]
I'm working on a project using Leaflet and overruling their standard tooltip layout doing something like this:

```css

:global {
  /*
    The custom-tooltip class is set on the map container to address and overrule the tooltip classes by using a higher selector specifity.
  */
  .custom-tooltip .leaflet-tooltip-left,
  .custom-tooltip .leaflet-tooltip-right,
  .custom-tooltip .leaflet-tooltip-top {
     composes: shadowBottomFilter from '../../shared-styles/base-classes';
}
```

This gives me an error:

```
Error: composition is only allowed when selector is single :local class name not in ".leaflet-tooltip-left,
  .leaflet-tooltip-right,
  .leaflet-tooltip-top", ".leaflet-tooltip-left" is weird
```

I'm not sure why this would not be allowed or is considered weird. What would be the correct approach you think?
