### ISSUE TITLE
Surprising behavior with Sass `.name &` syntax

### ISSUE THREAD

**Issue by smrq** [css-modules/css-modules#262]
The following SCSS...

```scss
:global {
  .container {
    background-color: red;
  }

  .foo {
    .container & {
      color: blue;
    }
  }
}
```

...gets compiled into...

```css
:global .container { background-color: red; }
.container :global .foo { color: blue; }
```

...which means that the first instance of `.container` will be left alone, but the second will get mangled.

This is technically correct from Sass's perspective, as it doesn't have any special casing for CSS Modules' scoping blocks, so `&` in that context refers to the selector `:global .foo`.

I can't think of a better way of resolving this than...

```
:global {
  .foo {
    :global(.container) & {
...
```

...which at first glance looks redundant, but is technically necessary.

Anyway, might be worth a mention in the [Usage with Preprocessors](https://github.com/css-modules/css-modules#usage-with-preprocessors) section of the readme?
