### ISSUE TITLE
composes vs. comma separated classnames

### ISSUE THREAD

**Issue by juliamio** [css-modules/css-modules#271]
Hey everybody 👋 

What are the benefits of using `composes` when in scope of the single file?

 Let's take:

```css
.button {
  display: block;
  cursor: pointer;
}

.button-special {
   composes: button;
   background-color: indianred;
}

``` 

versus 

```css
.button,
.button-special {
  display: block;
  cursor: pointer;
}

.button-special {
  background-color: indianred; 
}
```

I'm looking for the best way to solve similar case in quite a big system and I'm very curious about your thoughts on that.
