### ISSUE TITLE
Nested global rules with immediate child combinator

### ISSUE THREAD

**Issue by MattKunze** [css-modules/css-modules#273]
Thanks to [this comment](https://github.com/css-modules/css-modules/pull/65#issuecomment-294244374) I was able to figure out how to combine module-specific munged names with global styles so it's easier to work with existing CSS frameworks like Bootstrap.

So with Sass as a transpiler I can do something like the following to override framework styles localized to my component:

```css
.myComponent {
  padding: 1em;
  :global {
    .alert {
      margin-bottom: 0;
    }
  }
}
```

and this gives me something like:

```css
.myComponent___GBe9d {
  padding: 1em;
}
.myComponent___GBe9d .alert {
  margin-bottom: 0;
}
```

However, ideally I'd like the second rule to be `.myComponent___GBe9d > .alert` as a minor performance improvement, but I've tried adding the `>` combinator in a variety of ways in the source and everything ends up in some sort of compiler error:

```
Module build failed: Missing whitespace before :global (4:3)

  3 |   padding: 1em; }
> 4 |   .myComponent :global > .alert {
    |   ^
  5 |     margin-bottom: 0; }
```

I know I can also insert additional class names into the alert and override things that way, I was just trying to minimize the amount of 'class soup' we end up with, and keep a clearer separation between the classed used for our components vs the styles provided by the global framework

It's probably not that important in the end (I'm guessing the performance difference is negligible unless the markup is extremely complex, which is another issue itself), I was more just curious if it was possible.

**Comment by samsch** [comment]
I think I'm getting the same error, but in Bootstrap scss imported in a `:global {}` block.

```scss
:global {
  @import './node_modules/bootstrap/scss/bootstrap.scss';
}
```
```
🚨  /<project path>/test-parcel-bootstrap-css-module/styles.scss:346:5: Missing whitespace before :global
  344 |     color: #e83e8c;
  345 |     word-break: break-word; }
> 346 |     a > :global code {
      |     ^
  347 |       color: inherit; }
  348 |   :global kbd {
```
You can run a test case project by cloning from here: https://github.com/samsch/test-parcel-bootstrap-css-module

**Comment by cupofjoakim** [comment]
Also having this issue. Any pointers or suggestions on workarounds would be appreciated.

We're writing a component library, but for accessibility we need an external datepicker. This datepicker has an external stylesheet, and whilst our wrapper classes can be hashed, the datepickers classes can not. We can't even insert classes into that library, so we have to select it from outside.

The case for us looks something like this:
```scss
.datepicker {
  &--invalid > :global .SingleDatePickerInput__withBorder {
    border: 1px solid var(--red-500);
  }
}
```

which nets us an error that multiple people in this thread reported: 
```sh
Syntax error: Missing whitespace before :global (1:1)

> 1 | .datepicker--invalid > :global .SingleDatePickerInput__withBorder {
    | ^
  2 |   border: 1px solid var(--red-500); }
```
