### ISSUE TITLE
Import of selector

### ISSUE THREAD

**Issue by bripkens** [css-modules/css-modules#276]
Hi everyone,

is it possible to import selectors from other files and to use them within selectors? I am specifically looking for the following when translating existing style sheets:

```css
// File: Button.css
:local
  .button {
    // ...
  }

  .button + .button {
    margin-left: 1rem;
  }
}




// File: ButtonGroup.css
:local {
  composes: button from 'Button.css';
  
  .buttonGroup > button {
    margin-left: 0;
  }
}



// Combined Result (without local name modification)
.button {
  // ...
}

.button + .button {
  margin-left: 1rem;
}

.buttonGroup > .button {
  margin-left: 0;
}
```

The use case behind this is that of a component catalog that is implemented via React. Each React component has its own stylesheet (e.g. `Button.css` and `ButtonGroup.css`). Thank you for your help!

**Comment by kapowaz** [comment]
I came here to post a similar issue, which I think would be solved by the introduction of this feature. To clarify (since the context I need is subtly different), here is how I’d see it working (we use CSS Modules with React and Sass, so for convenience so do the examples below).

First of all, let’s say we have a React component called `<Button>`, which has a stylesheet applied using CSS Modules:

```scss
// Button.scss
.button {
  border: 1px solid;
  border-radius: 2px;
  // etc.
}
```

If we then had another component called `<ButtonGroup>` we might then want to change the styles of `<Button>` dependent on the properties of `<ButtonGroup>` itself. Currently there is no way of doing this without passing props through to the child which then trigger applying another class _inside_ the child component. This approach doesn’t scale particularly well, however, and it would be great if we could make use of the original benefits of specificity by creating something like this

```scss
// ButtonGroup.scss
@import .button from '../Button.scss';

.buttonGroup {
  display: flex;
  
  @include maxWidth(tabletSmall) {
    flex-direction: column;
  }

  .button {
    flex: 1;

    & + .button {
      @include maxWidth(tabletSmall) {
        margin-top: 16px;
      }
    
      @include minWidth(tabletSmall) {
        margin-left: 16px;
      }      
    }
  }
}
```

CSS Modules would then need to ensure that the generated classname in the output of `ButtonGroup.scss` was identical to the one generated within `Button.scss`.

I see lots of advantages to this kind of syntax beyond the ability to override the child component from the parent:

* It would allow a component to use selectors to define the relationship between itself and its siblings,  e.g. `.textInput + .button`.
* Since it has an explicit API, unintentional usage would be unlikely, and so the increased specificity of selectors is almost certainly by design.
* Responsibility for overriding styles would belong with the parent, and so the dependency graph of styles would most accurately reflect actual usage; if a page uses `<SomeComponent>` but not `<ParentComponentOfSomeComponent>` it wouldn’t include any unnecessary CSS.
* Similarly, if the parent component is removed, its stylesheet can be safely removed along with it; whereas when we pass a prop to trigger another class in the _child_, we need to know that the child also needs to be modified if the code path becomes dead.

Your thoughts on this are appreciated!
