### ISSUE TITLE
Is it possible to selectively import classes into a component?

### ISSUE THREAD

**Issue by berikiushi** [css-modules/css-modules#277]
I have a style file with several classes, for example:

```css
/* style.css */
.className {
  color: green;
  background: red;
}

.otherClassName {
  composes: className;
  color: yellow;
}
```

and I want to use only the `.className`. I import  it like

`import { className } from "./style.css";`

it works, but the unused `.otherClassName` is still present in the loaded styles, so it should be?
