### ISSUE TITLE
Nested global no longer working after switching from .less to .scss

### ISSUE THREAD

**Issue by MartinDawson** [css-modules/css-modules#292]
Before, when I was using local css modules I could do this:

```css
.footer {
  position: relative;

  > a {
    margin: 10px;
  }
}
```

outputs incorrectly:

```css
.Components-footer-footer__footer {
  position: relative;

  > a {
    margin: 10px;
  }
}
```

This treated `> a` as a global selector automatically because their was no class name attached to it.

Now I have to do this:

```css
.footer {
  position: relative;
}

.footer > :global(a) {
  margin: 10px;
}
```

outputs correctly:

```css
.Components-footer-footer__footer {
  position: relative;
}

.Components-footer-footer__footer > a {
  margin: 10px;
}

```

```js
{
        test: /\.s?css$/,
        exclude: /node_modules/,
        use: ExtractTextPlugin.extract({
          fallback: 'style-loader',
          use: [{
            loader: 'css-loader',
            options: {
              importLoaders: 1,
              modules: true,
              localIdentName: '[path][name]__[local]',
            },
          }, {
            loader: 'postcss-loader',
            options: {
              config: {
                path: path.resolve(__dirname, 'postcss.config.js'),
              },
            },
          }],
        }),
      },
```

Has something changed or am I missing some config variable?
