### ISSUE TITLE
do not return the names of global classes

### ISSUE THREAD

**Issue by budarin** [css-modules/css-modules#293]
styles.css

```css
:global .hello { color: blue }
```
code:
```js
import styles from './styles';

return <div className={css.hello}>Hello World!</p>;
```
raises the error: ```Uncaught TypeError: Cannot read property 'hello' of undefined```

Is it default behavior or it's a bug?
