### ISSUE TITLE
How to use :global and :local styling with & (ampersand) ?

### ISSUE THREAD

**Issue by orszaczky** [css-modules/css-modules#295]
How do I reference the :local parent in the :global scope?

This works:
```
.local-parent {
  :global {
    .global-class-name {
      color: green;
    }
  }
}
```
But this throws an error:

```
.local-parent {
  :global {
    &.global-class-name {
      color: green;
    }
  }
}
```

**Comment by rphelan** [comment]
Try this:
```
:global {
  :local(.local-parent) {
    &.global-class-name {
      color: green;
    }
  }
}
```

**Comment by nadavofi** [comment]
Worked for me, thanks @rphelan !

**Comment by hueralin** [comment]
@rphelan it works，thank you~

**Comment by 791106912** [comment]
> That's also works!
> 
> ```css-less
> .local-parent {
>    &:global(.global-class-name) {
>      color: red;
>    }
> }
> ```

Thank you! It is works for me.

**Comment by 791106912** [comment]
@BovineBoy  Thank you! It is works for me.

**Comment by avennn** [comment]
> That's also works!
> 
> ```css-less
> .local-parent {
>    &:global(.global-class-name) {
>      color: red;
>    }
> }
> ```

I think this is much better.

**Comment by 791106912** [comment]
邮件已经收到，谢谢，虽然我极有可能不看QQ邮箱。

**Comment by domehead100** [comment]
I think this also works (just prefix the :global block with an ampersand).

```css
.local-parent {
  &:global {
    &.global-class-name {
        color: red;
    }
  }
}
```
This works for me (React project with sass-loader and react-css-modules webpack plugin).

The approach listed above...

```css
:global {
  :local(.local-parent) {
    &.global-class-name {
      color: green;
    }
  }
}
```
does not work in my case because it causes the css to apply global-class-name to the local-parent's descendants instead of the local-parent.  (in my case .local-parent is at the top level, as is typical with css modules) rather than as above where :global is at the top level.
