### ISSUE TITLE
Preprocessor Compatibility?

### ISSUE THREAD

**Issue by stereokai** [css-modules/css-modules#30]
This project is very innovative, and at the right direction too! But correct me if I'm wrong, things like this:

```CSS
.normal {
  composes: common;
  composes: primary from "../shared/colors.css";
}
```

Would break the very strict Sass compiler, no?
