### ISSUE TITLE
Reference class from other module

### ISSUE THREAD

**Issue by birjolaxew** [css-modules/css-modules#319]
How would I go about referencing a class from another class?

```css
/* == Sheet1.css
 * Should expose: { arrow: "compiled--arrow" } */
.arrow { color: red; }

/* == Sheet2.css
 * Should expose: { green-select: "compiled--green-select" } */
.green-select {
  :sheet1(.arrow) { /* how do */
    color: green;
  }
}
```

I am interested in replacing "`.arrow`" in Sheet2.css with whatever the compiled name of "`.arrow`" in Sheet1.css is. Only `.green-select` would have to be exported from the CSS module, as `.arrow` isn't a local class.

The only workaround I can think of is using `:global(.arrow)` in Sheet1.css and Sheet2.css. This would kind of ruin the entire point of CSS modules, especially if this is needed in many places. At that point you're back to using plain CSS.

**Comment by gbirke** [comment]
Have you tried using `compose`? 
Example:

```css
/* == Sheet2.css
 * Should expose: { green-select: "compiled--green-select" } */
.green-select {
    compose: arrow from 'Sheet1.css'
    color: green;
}
```
