### ISSUE TITLE
Recommended way to "extend" native HTML elements

### ISSUE THREAD

**Issue by peduarte** [css-modules/css-modules#32]
Hello,

I've been experimenting with css-modules and came across an issue to which I found no sensible solution for.

I would like to know how I can create `variables` with css-modules and re-use them across my CSS components. I am aware that the workflow with css-modules is a little different than with Sass/Less, but take this as an example:

**The sass way***
```sass
// variables
$size-small: 0.8em;
$color-faded: #eee;

// rules
small {
  font-size: $size-small;
}

footer p {
  color: $color-faded;
}
```

**css-modules way... well, what I tried anyway**
```sass
// typography.css
.small {
  font-size: 0.8em;
}

// colors.css
.faded {
  color: #eee;
}

// rules
small {
  composes: small from 'typography.css';
}

footer p {
  composes: faded from 'colors.css';
}
```

But we cannot use `composes` in native HTML elements.

What am I missing here?
Maybe I am approaching this the wrong way?

If the solution is to add a class to every element, then... goodbye css-modules 👋

Any advice, recommendation or insults will be very helpful.

👊

**Comment by henriquea** [comment]
+1

This is an issue if you're using for example markdown-loader or any third-party where it returns pure html. We'd have to overwrite the loader to add a className to the elements.

Keen to know what is the best way to achieve this.

I'm going to cc @markdalgleish the godfather of CSS modules 😄

**Comment by nkbt** [comment]
The solution is to add a class to every element you want to style.

**Comment by nkbt** [comment]
For 3rd party html use `:global`.

**Comment by henriquea** [comment]
@nkbt not really a solution when you're dealing with 3rd party and can't just drop a `:global`. To be honest I don't mind to style each one but I guess my friend @peduarte will get mad at this 😂

**Comment by peduarte** [comment]
That is not a solution. It is merely a workaround!

Why would you sacrifice the basic behaviour of CSS? 

I have a better solution which I will post here later.

**Comment by peduarte** [comment]
Ok first, I am extremely disappointed with the lack of essential documentation.

I think it's selfish that a a tool such as this is released without informing users that the most common thing CSS is used for will not work.

I think by now every half-decent front end developer understand that isolating and modularising your UI Components is a good thing, but frankly, it is something that can be done with CSS alone.

Tools like this is not supposed to remove the default functionality of CSS, it is supposed to enhance it, and take it to the next level.

I think that whoever is responsible for this documentation, all the developers writing articles about css-modules hoping to get more Twitter followers should let their readers know. 

On a separate note, here is a *half-decent* solution, if someone is really that desperate to use this *half-built* tool:

Based on my current workflow: webpack + react + css-loader + postcss-loader + cssnext-loader

***Refactored/simplified for example purpose***

**base.css**
We use *cssnext* to define our variables and custom media queries
```css
:root {
  --color-text: #333;

  --size-s: 1.618rem;
  --size-l: 4.236rem;
}

@custom-media --medium-viewport (min-width: 768px);
```
**typography.css**
Shared component – supposed to be extended by using css-module's `compose` 😂
```css
/* Get access to cssnext variables */
@import './base.css';

.small {
  font-size: var(--size-s);
}

.large {
  font-size: var(--size-l);
}
```
**color.css**
Shared component – supposed to be extended by using css-module's `compose` 😂
```css
/* Get access to cssnext variables */
@import './base.css';

.text {
  color: var(--color-text);
}
```
**global.css**
This is where you can define some default styling for native html elements
```css
@import './base.css';

body {
  /* half-decent solution */
  font-size: var(--size-s);

  /* ideal solution */
  composes: small from './typography.css';
}

h1 {
  /* half-decent solution */
  font-size: var(--size-l);

  /* ideal solution */
  composes: large from './typography.css';
}

p {
  /* half-decent solution */
  color: var(--color-text);

  /* ideal solution */
  composes: text from './color.css';
}
```
**component.css**
This is your component, the CSS here will be namespaced (what css-modules is for)
```css

/* component title */
.title {
  /* Here it works because this is not a HTML element selector */
  composes: color from './color.css'
}

```
<br>
Although this solution is not perfect, using *cssnext* allows me to still have my variables and custom media queries which can be used to style native HTML selector and used to extend my CSS modules.

I am happy to hear if anything else has found a nicer approach.

/cc @henriquea @markdalgleish 

✌️
