### ISSUE TITLE
JavaScript heap out of memory when importing self

### ISSUE THREAD

**Issue by boukeversteegh** [css-modules/css-modules#327]
Short description:
- When importing the file from itself, an infinite recursion happens and Node crashes.
- A detection of this type of mistake could help users figure out the problem more quickly.

During a refactoring, I merged two files:

```css
/* parent.css */
.node {
    /* style */
}
```

```css
/* child.css */
.node {
  composes: node from './parent.css'
}
```

and recompiled:

```css
/* parent.css */
.node {
    /* style */
}
.node {
  composes: node from './parent.css'
}
```

Upon recompile, I node crashed:

    FATAL ERROR: invalid array length Allocation failed - JavaScript heap out of memory

Upon inspection, of course, it is importing `./parent.css` from `./parent.css`, causing an infinite recursion, and memory exhaustion.

Unfortunately, CSS-modules does not detect this mistake, and report a warning, so it took some selective undoing of refactorings until I found the error.

A check for this type of mistake would be very helpful.

Kind regards, Bouke
