### ISSUE TITLE
Is it possible to make global blocks with SASS?

### ISSUE THREAD

**Issue by Hubro** [css-modules/css-modules#337]
The README shows an example of how to make global blocks in less:

```less
:global {
  .global-class-name {
    color: green;
  }
}
```

Is there any way to make such a block using SASS?

The obvious way doesn't work:

```sass
.form-section
    margin-top: 30px

    :global
        h2.subtitle
            margin-bottom: 5px

        p
            margin-bottom: 20px
```

![image](https://user-images.githubusercontent.com/597206/75277476-5ce95680-5808-11ea-99d1-3fd88d6b29e0.png)
