### ISSUE TITLE
Question. Hierarchical composes result in long lists of classnames in the DOM.

### ISSUE THREAD

**Issue by eagor** [css-modules/css-modules#341]
I've split styling into small reusable css modules, and a simple button with styling for `button` and `layout` ended up to have long list of classnames:

 ```html
<a class="toggle-button_toggle__2BK-L layout_paddingVerticalSmall__1Ckkp
layout_paddingTopSmall__3wD-S layout_paddingBottomSmall__2AdXn
layout_paddingHorizontalMedium__3Y30Y layout_paddingLeftMedium__bgfqC
layout_paddingRightMedium__2kDYS" href="/">...</a>
```

and the code is this:

```css
/* toggle-button.module.css */
.toggle {
	/* ... */
	composes: paddingVerticalSmall paddingHorizontalMedium from "../layout.module.css";
}
```

```css
/* layout.module.css */

.paddingTopSmall {
	padding-top: var(--spacing-small);
}
.paddingBottomSmall {
	padding-bottom: var(--spacing-small);
}
.paddingVerticalSmall {
	composes: paddingTopSmall paddingBottomSmall;
}

.paddingRightMedium {
	padding-right: var(--spacing-medium);
}
.paddingLeftMedium {
	padding-left: var(--spacing-medium);
}
.paddingHorizontalMedium {
	composes: paddingLeftMedium paddingRightMedium;
}
```

That's just the simplest example. Imagine importing some more styling for typography, colors, sizes, and the list of classnames would grow even more.

Is there a better way to do it? Or any bad practice against what I'm doing?
