### ISSUE TITLE
Is there a way to import class from another file?

### ISSUE THREAD

**Issue by lastnigtic** [css-modules/css-modules#342]
I have two css and I want to use then same class from other file
`
// a.css
:local(.container) {
  position: relative
}
`

`
// b.css
.container { 
  p {
    line-height: 36px;
  }
}
`
In this situation, '.container' in a and '.container' in b is different after compile.

Is there a way to achieve this?

Thanks for you help!

**Comment by pascalduez** [comment]
This is usually achieved with composition:

```css
/* a.css */
.container {
  ...
}

/* b.css */
.whatever { 
  composes: container from "./a.css";
  ...
}
```

**Comment by lastnigtic** [comment]
```
<div class='container'>
  <div class='a'></div> // write a.css in this component
  <div class='b'></div> // write b.css in this component
</div>
```

I just want class a's style only works under container and keep class a's declare.

Any suggestions? Thanks for your help

**Comment by blm768** [comment]
The [ICSS `:import` syntax](https://github.com/css-modules/icss#import) seems like it'd be basically perfect for this based on the spec. Unfortunately, at least with Vite + PostCSS, `:import` seems to pull in the style definitions from the target file and disable hashing for the aliased class rather than pulling in the aliased name and substituting it throughout the target file.

**Comment by tivac** [comment]
This sounds like what the `:external()` proposal from https://github.com/css-modules/css-modules/issues/147 does, but it was never added or implemented in CSS Modules.

**Comment by lastnigtic** [comment]
Yes, it may be a suitable solution.

**Comment by futpib** [comment]
Here is a hacky workaround for https://github.com/css-modules/css-modules/issues/342#issuecomment-602328856 based on css variables: https://jsfiddle.net/0uLv47px/10/

The gist of it is this:
```css
.a {
	background: var(--a-bg);
}

.container > * {
	--a-bg: var(--a-bg-under-container);
}

.container > * > * {
	--a-bg: var(--a-bg-default);
}
```
