### ISSUE TITLE
Override problem, perfect for a single file, how to deal with multiple files?

### ISSUE THREAD

**Issue by ilovedesert001** [css-modules/css-modules#347]
```scss
.myBlock {
  color: green;
  .a1 {
    color: blue;
    background: green;
  }
}

.myBlock2 {
  color: green;
  .a1 {
    background: red;
    color: white;
  }
}


// How should I implement this part of the function in other scss files?

:global(.section) {
  .myBlock2 {
    .a1 {
      background: gray;
      color: black;
    }
  }
}

// this need to be in  page.module.scss file
:global(.page) {
  :global(.section) {
    .myBlock2 {
      .a1 {
        background: green;
        color: white;
      }
    }
  }
}

```

tsx

```tsx
      <div>
        <div className={style.myBlock}>
          <div className={style.a1}>block</div>
        </div>

        <div className={style.myBlock2}>
          <div className={style.a1}>block</div>
        </div>

        <div className={"section"}>
          <div className={style.myBlock2}>
            <div className={style.a1}>block</div>
          </div>
        </div>
        <div className="page">
          <div className={"section"}>
            <div className={style.myBlock2}>
              <div className={style.a1}>block</div>
            </div>
          </div>
        </div>
      </div>

```
