### ISSUE TITLE
Bad imported 'composes' identifiers fail silently

### ISSUE THREAD

**Issue by ekelen** [css-modules/css-modules#356]
If a class name from a valid external file does not exist, no error is thrown and the rule fails silently. Since treating CSS classes as true dependencies is one of the most valuable features of this package, it seems this should be supported.

./fileName.css
```css
.box { display: flex; }
```

./index.jsx
```jsx
import styles from './composing.css'
...
<div className={styles.root}/>
```

./composing.css
```css
/* throws 👍 */
.root {
  composes: box from "./badFileName.css";
  border-style: dotted;
  border-color: green;
}
```

./composing.css
```css
/* fails silently ☹️ */
.root {
  composes: doesntexist from "./fileName.css";
  border-style: dotted;
  border-color: green;
}
```
