### ISSUE TITLE
Combine scss nested classes and child operator with the css-modules package

### ISSUE THREAD

**Issue by rickstaa** [css-modules/css-modules#359]
Judging from this StackOverflow past nested [scss](https://sass-lang.com/documentation/syntax) classes are supported by the [css-modules](https://github.com/css-modules/css-modules/issues/new) package when a project is created using [create-react-app v2](https://create-react-app.dev/). In this case, CSS modules then put nested classes directly under the object. I use the following scss file to style a class that is contained in another third-party react component:

```scss
.piano-module {
  position: fixed;

  .container {
    padding: 10px 30px;

    .wrapper {
      width: 100%;

      .piano > .ReactPiano__Key--accidental {
        background: #000000;
      }

      .piano > .ReactPiano__Key--natural {
        background: #ffffff;
      }

      .piano > .ReactPiano__Key--active.ReactPiano__Key--accidental {
        background: #0396ca;
      }

      &.piano > .ReactPiano__Key--active.ReactPiano__Key--natural {
        background: #0396ca;
      }
    }
  }
}
```

with the following html:

```js
import styles from "./PianoModule.module.scss";

const PianoModule = () => {
  console.log(styles);
  return (
    <div className="piano-module">
      <div className="container">
        <div className="wrapper">
          <ResponsivePiano className="piano"></ResponsivePiano>
        </div>
      </div>
    </div>
  );
};
```

When I'm trying to replace this with css-modules the styling doesn't seem to work:

```js
import styles from "./PianoModule.module.scss";

const PianoModule = () => {
  console.log(styles);
  return (
    <div className="piano-module">
      <div className="container">
        <div className="wrapper">
          <ResponsivePiano className={styles.piano}></ResponsivePiano>
        </div>
      </div>
    </div>
  );
};
```

When I check the `styles` object, I see it contains the following auto-generated classes:

![image](https://user-images.githubusercontent.com/17570430/103656675-2d979000-4f69-11eb-8e30-fcf0d88d5da8.png)

I noticed, however, that in this case that child styles `>` do not get applied. This is not strange as now the `PianoModule_ReactPiano__Key--accidental` has been changed to `PianoModule_ReactPiano__Key--accidental__39cTL`. I tried to fix this using the following syntax. My question therefore is:

- Is it possible to use scss operations like nested classes and the child operator with css-modules?

### Using the postcss-nested module

- I used the [craco](https://github.com/gsoft-inc/craco) package to add the [postcss-nested](https://github.com/postcss/postcss-nested) plugin.

## Related issues

- #139 I think my problem is related to this feature request.
- #102 I think it is also related to this feature request.
- #349 Create-react-app v2 already includes the sass-loader.
- [#273](https://github.com/css-modules/css-modules/issues/273#issuecomment-597677979) Adding the global() operator does cause the child styles to be applied.
