### ISSUE TITLE
Issue with duplicate class hashes 

### ISSUE THREAD

**Issue by lynxionxs** [css-modules/css-modules#387]
Is there a way to make utility classes only hash once and reuse everywhere ?
Instead of a different hash for each class in a component.

Example ```.flex-absolute-center``` utility class is used in 100 components.
Now each of those components creates a different hash for each, like,
```.flex-absolute-center_Wk4``` ```.flex-absolute-center_A3O```
Is there a way to use ```.flex-absolute-center_Wk4``` in all the 100 components instead ?  
Production will be one hash ```.u39nin9Ujk4_```

```css
.flex-absolute-center {
  display: flex;
  justify-content: center;
  align-items: center;
}
```
