### ISSUE TITLE
Does the order of implementation of a class matter when there are two classes with the same parameters?

### ISSUE THREAD

**Issue by shezhangzhang** [css-modules/css-modules#388]
Let's say we have a jsx like this:
```jsx
<div className={`${styles.class1} ${styles.class2}`}>result</div>
```
1. result is red.
```css
.class1 {
  color: blue;
}
.class2 {
  color: red;
}
```
2. result is blue.
```css
.class2 {
  color: red;
}
.class1 {
  color: blue;
```
