### ISSUE TITLE
Rules nesting

### ISSUE THREAD

**Issue by velosipedist** [css-modules/css-modules#397]
As the working draft were [implemented](https://developer.chrome.com/articles/css-nesting/) in most of the browsers, it would be great to support the nesting here as well.

```css
.demo {
  & .circle {
    opacity: .25;
    filter: blur(25px);
  }
  > .square {
    color: red;
  }
}
```

**Comment by pascalduez** [comment]
Hello,

I was curious so just did a quick test, seems so nesting is currently supported? 
https://codesandbox.io/s/jovial-neco-whpg94?file=/src/Test.module.css

The compiled CSS properly keep the nesting, classes are scoped.   

At least with this implementation, which I believe is create-react-app, css-loader etc.

**Comment by JuanPastenCastillo** [comment]
At least, for now you can use it this way on Nextjs:

```javascript
// Component.tsx
import styles from "./Styles.module.css"

export const CSS_Modules = () => {
  return (
    <div className={styles.css}>
      <h2 className={styles.h2}>Some H2</h2>

      <h2>Other h2</h2>

      <h2>More h2!</h2>
    </div>
  )
}
```

```CSS
/* Styles.module.css */
.css {
  border: 2px solid black;

  .h2 {
    border: 2px solid crimson;
    color: red;
  }

  &.css > :nth-child(2) {
    border: 2px solid green;
    color: green;
  }

  &.css :nth-child(3) {
    border: 2px solid yellow;
    color: yellow;
  }
}
```

Result:

![image](https://github.com/css-modules/css-modules/assets/46139914/e6898472-156c-4261-946a-e51497ac5a80)
