### ISSUE TITLE
Understanding "composes" peer classes

### ISSUE THREAD

**Issue by douglasjunior** [css-modules/css-modules#398]
I'm trying to use `composes` with multiple class levels, but it's working for part of my need.

My project is configured with `vite` and `lightningcss`.

I have the following scenario:

## `component.module.css`

```css
.classA {
  composes: fontSizes--headingMedium from global;
  background-color: magenta;
}

.classB {
  composes: classA from '.';
  text-align: center;
}

.myComponentClass {
  composes: classB from '.';
  border: solid 1px red;
}
```

## `theme.css` (imported globally in my `App.tsx`)

```ts
.fontWeights--bold {
  font-family: Arial, sans-serif, NunitoSans-Bold;
  font-weight: bold;
}

.fontSizes--headingMedium {
  composes: fontWeights--bold from '.';
  font-size: 24px;
  line-height: 24px;
  letter-spacing: 0;
}
```

## Result appearance

<img width="694" alt="image" src="https://github.com/css-modules/css-modules/assets/1512341/2710df52-274d-4e65-8305-d32edb551a5d">

## Result HTML

<img width="625" alt="image" src="https://github.com/css-modules/css-modules/assets/1512341/181e3e4b-5cb8-4fff-92a7-abd16c072929">

## Result CSS

<img width="455" alt="image" src="https://github.com/css-modules/css-modules/assets/1512341/debe0a32-e5f0-456d-b32e-045a387277e1">

So, note that the `composes: fontWeights--bold from '.';` was ignored by the css-modules transpilation.

What I'm doing wrong?

Reproducible example: https://codesandbox.io/p/sandbox/lightningcss-css-modules-composition-demo-6k9x67
