### ISSUE TITLE
Is there a way to support native nesting selector `& &`?

### ISSUE THREAD

**Issue by MangelMaxime** [css-modules/css-modules#412]
With modern CSS, we now have access to the nesting selector `&`.

```css
.flex-table {
    & &__header {
        display: flex;
        align-items: center;
        padding: 0 10px;
    }
}
```

When targeting old browser in the past I didn't have any trouble because it was generating something like:

```css
.flex-table { ... }
.flex-table .flex-table__header {...}
```

which means that I had access to the full class `flex-table__header`.

However, because modern browser are gaining support of `&` natively, then depending on the browserlist configuration we don't always have the full class generated.

Is it possible to support such syntax with CSS Modules or do I need to be careful about not using `& &` trick anymore?

> [!NOTE]
> `& &` trick, was handy because by renaming the top level class all nested reference where automatically renamed too.

**Comment by JuanPastenCastillo** [comment]
[Here](https://codesandbox.io/s/jovial-neco-whpg94?file=/src/Test.module.css) [pascalduez](https://github.com/pascalduez) made an example with native css and css modules with nesting. It seems to work.

The comment comes from [here](https://github.com/css-modules/css-modules/issues/397#issuecomment-1683893607)

**Comment by JuanPastenCastillo** [comment]
On Nextjs you can do something like this:

```javascript
// Component.tsx
import styles from "./Styles.module.css"

export const CSS_Modules = () => {
  return (
    <div className={styles.css}>
      <h2 className={styles.h2}>Some H2</h2>

      <h2>Other h2</h2>

      <h2>More h2!</h2>
    </div>
  )
}
```

```CSS
/* Styles.module.css */
.css {
  border: 2px solid black;

  .h2 {
    border: 2px solid crimson;
    color: red;
  }

  &.css > :nth-child(2) {
    border: 2px solid green;
    color: green;
  }

  &.css :nth-child(3) {
    border: 2px solid yellow;
    color: yellow;
  }
}
```

Result:

![image](https://github.com/css-modules/css-modules/assets/46139914/e6898472-156c-4261-946a-e51497ac5a80)
