### ISSUE TITLE
support composes inside pseudo-element 

### ISSUE THREAD

**Issue by fraserxu** [css-modules/css-modules#42]
I have some CSS looks like this:

```CSS
.button {
  composes: button from './component/button.css';

  color: #fff;
}

.icon {
  /* style to add an icon before a button*/
  position: absolute;
  top: 50%;
  width: 20px;
  height: 20px;
  line-height: 20px;
  margin-top: -10px;
  font-size: 14px;
}

.button::before {
  composes: icon;

  /* some custom option */
  left: 30px;
  content: 'T';
}
```

But got an error saying `Module build failed: Error: composes is only allowed when selector is single :local class name not in ":local(.button)::before"`

`composes` seems only work for normal selector without `pseudo`. Is there a way to support using `composes` inside a pseudo-element?

More details of the error message:

```
./~/css-loader?modules&importLoaders=1&localIdentName=[name]__[local]___[hash:base64:5]!./~/postcss-loader!./src/pages/Regional/regional.css
Module build failed: Error: composes is only allowed when selector is single :local class name not in ":local(.distractName)::before"
    at /Users/fraserxu/code/work/CVR-candidate-module/node_modules/css-loader/node_modules/postcss-modules-scope/lib/index.js:22:13
    at Array.map (native)
    at getSingleLocalNamesForComposes (/Users/fraserxu/code/work/CVR-candidate-module/node_modules/css-loader/node_modules/postcss-modules-scope/lib/index.js:20:26)
    at /Users/fraserxu/code/work/CVR-candidate-module/node_modules/css-loader/node_modules/postcss-modules-scope/lib/index.js:106:26
    at /Users/fraserxu/code/work/CVR-candidate-module/node_modules/css-loader/node_modules/postcss/lib/container.js:131:34
    at /Users/fraserxu/code/work/CVR-candidate-module/node_modules/css-loader/node_modules/postcss/lib/container.js:102:26
    at Rule.each (/Users/fraserxu/code/work/CVR-candidate-module/node_modules/css-loader/node_modules/postcss/lib/container.js:89:22)
    at Rule.eachInside (/Users/fraserxu/code/work/CVR-candidate-module/node_modules/css-loader/node_modules/postcss/lib/container.js:101:21)
    at Rule.eachDecl (/Users/fraserxu/code/work/CVR-candidate-module/node_modules/css-loader/node_modules/postcss/lib/container.js:129:25)
    at /Users/fraserxu/code/work/CVR-candidate-module/node_modules/css-loader/node_modules/postcss-modules-scope/lib/index.js:105:12
    at /Users/fraserxu/code/work/CVR-candidate-module/node_modules/css-loader/node_modules/postcss/lib/container.js:141:30
    at /Users/fraserxu/code/work/CVR-candidate-module/node_modules/css-loader/node_modules/postcss/lib/container.js:102:26
    at Root.each (/Users/fraserxu/code/work/CVR-candidate-module/node_modules/css-loader/node_modules/postcss/lib/container.js:89:22)
    at Root.eachInside (/Users/fraserxu/code/work/CVR-candidate-module/node_modules/css-loader/node_modules/postcss/lib/container.js:101:21)
    at Root.eachRule (/Users/fraserxu/code/work/CVR-candidate-module/node_modules/css-loader/node_modules/postcss/lib/container.js:139:21)
    at /Users/fraserxu/code/work/CVR-candidate-module/node_modules/css-loader/node_modules/postcss-modules-scope/lib/index.js:101:9
 @ ./src/pages/Regional/regional.css 4:14-206 13:2-17:4 14:20-212
```

**Comment by geelen** [comment]
Hey there, you might be interested to read the discussion here: https://github.com/css-modules/css-modules/issues/33#issuecomment-135964824

Short answer, you can't do that — `composes` doesn't work in that way. Here's a solution to your problem though:

```css
.icon {
  /* maybe something here, maybe nothing */
}

.icon::before {
  /* style to add an icon before a button*/
  position: absolute;
  top: 50%;
  width: 20px;
  height: 20px;
  line-height: 20px;
  margin-top: -10px;
  font-size: 14px;
}

.button {
  composes: button from './component/button.css';
  composes: icon;
  color: #fff;
}
```

When you compose something, you get all of its styles, all its pseudo selectors, everything, because you're actually just adding the `icon` class to your element.

Hope this clears it up!

**Comment by fraserxu** [comment]
Aha, that makes sense to me. Since `pseudo-element` is also part of the selector, it is reasonable to be composed inside the selector.

Thanks for the quick answer.

**Comment by jeron-diovis** [comment]
Have a similar issue. 
My code looks like this:
```CSS
.myClass tagName {
    composes: anotherClass;
}
```
It produces same error as above:
```
Error: composes is only allowed when selector is single :local class name not in ":local(.myClass) tagName"
```

Is it correct that composition is allowed **only** for classes?
