### ISSUE TITLE
Alias for a filename?

### ISSUE THREAD

**Issue by olegstepura** [css-modules/css-modules#45]
When I see this example:
```css
.article {
  composes: flex vertical centered from "./layout.css";
}

.masthead {
  composes: paragraph-margin-below from "./layout.css";
  /* ... */
}

.body {
  composes: max720 paragraph-margin-below from "./layout.css";
}
```
the question arises - what if I change file location or a name? I would have to walk over all `composes` rules and replace the filepath with a new one. Maybe it's worth introducing file aliases in the beginning of the CSS file. This solves:

* easier refactoring
* all imports are easily observed just by looking at the file heading
* may lead to less typing ;)

Simple example may be (mimics es6 import syntax):
```css
@require * as layout from "./layout.css";

.article {
  composes: flex vertical centered from layout;
}

.masthead {
  composes: paragraph-margin-below from layout;
  /* ... */
}

.body {
  composes: max720 paragraph-margin-below from layout;
}
```

it can also allow doing this:
```css
@require flex from "./layout.css";

.article {
  composes: flex;
}
```
