### ISSUE TITLE
Provide documentation for :import and :export

### ISSUE THREAD

**Issue by gajus** [css-modules/css-modules#52]
ICSS spec defines two methods `:import` and `:export`.

I am trying to use them with webpack [`style-loader`](https://github.com/webpack/style-loader), e.g.

`default.css`

```css
.squareShape {
    width: 10px;
    height: 10px;
}

```

`custom.css`

```css
:import('./default.css') {
    defaultSquare: squareShape;
}

.test {
    composes: defaultSquare;
    color: #f00;
}
```

This produces:

```css
.default__squareShape___2yjy0 {
    width: 10px;
    height: 10px;
}
.custom__test___2tYf3 {
    color: #f00;
}
```

am I doing something wrong?

The documentation is lacking and I am not getting an error.

**Comment by gajus** [comment]
In fact, even the syntax in [CSS Modules `README.md`](https://github.com/css-modules/css-modules#dependencies) seem to do nothing:

```css
.test {
    composes: squareShape from './default.css';

    color: #f00;
}
```

Produces:

```css
.default__squareShape___2yjy0 {
    width: 10px;
    height: 10px;
}
.custom__test___2tYf3 {

    color: #f00;
}

/*# sourceMappingURL=app.css.map*/
```

**Comment by gajus** [comment]
I am obviously doing something wrong because even:

```css
.bgColor {
    background: #f00;
}

.test {
    composes: bgColor;

    color: #f00;
}
```

Produces:

```css
.custom__bgColor___26vMp {
    background: #f00;
}

.custom__test___2tYf3 {

    color: #f00;
}

/*# sourceMappingURL=app.css.map*/
```

**Comment by gajus** [comment]
Facepalm. I have spent too much time working with preprocessors.

**Comment by gajus** [comment]
In case someone else stumbles upon this, `style-loader` does not merge two classes. It combines the selectors, e.g.

`styles.css`:

```css
.bgColor {
    background: #f00;
}

.test {
    composes: bgColor;

    color: #f00;
}
```

`index.js`:

```js
import styles from './styles.css';

`<div class={styles.test}></div>`
```

will produce the following HTML:

```
<div class='bgColor test'></div>
```
