### ISSUE TITLE
Nesting class definitions to reduce repeating "composes" rules

### ISSUE THREAD

**Issue by Daiz** [css-modules/css-modules#55]
So I read [this article](http://glenmaddern.com/articles/css-modules) talking about CSS modules and in step 2 it shows this piece of CSS:

```css
.common {
  /* all the common styles you want */
}
.normal {
  composes: common;
  /* anything that only applies to Normal */
}
.disabled {
  composes: common;
  /* anything that only applies to Disabled */
}
.error {
  composes: common;
  /* anything that only applies to Error */
}
.inProgress {
  composes: common;
  /* anything that only applies to In Progress */
}
```

And the repetition of `composes: common` instantly jumped out to me. From working in Less (or really, any of the popular alternatives), you could do this kind of "common and flavors" kind of styling like so:

```css
.common {
  /* all the common styles you want */
  &.normal { /* the & makes this translate to .common.normal, just in case you weren't aware */
    /* anything that only applies to Normal */
  }
  &.disabled {
    /* anything that only applies to Disabled */
  }
  &.error {
    /* anything that only applies to Error */
  }
  &.inProgress {
    /* anything that only applies to In Progress */
  }
}
```

And bam, you're not repeating the `composes: common` for the common stuff anymore.

I couldn't find any reference to if this was possible with CSS modules, which is why I'm opening this issue about it.
