### ISSUE TITLE
Idea: managing state

### ISSUE THREAD

**Issue by rafaelrinaldi** [css-modules/css-modules#67]
What if we had a way to define component states via CSS Modules?

```css
:state(disabled) {
  cursor: not-allowed;
}
```

Benefits I can think of:

* Better than having a local `.disabled` IMO;
* Makes integration with React (and even Angular) easier/cleaner when passing styles to the module.

<sup>Ps.: Originally proposed to @geelen [via Twitter](https://twitter.com/rafaelrinaldi/status/650452882949545984). I've created the issue just in case.</sup>

**Comment by nkbt** [comment]
What is wrong with `:disabled`?
```css
.button:disabled {
  cursor: not-allowed;
}
```

**Comment by rafaelrinaldi** [comment]
@nkbt I was just giving an example. Here is another one:

```css
:state(visible) {
  color: blue;
}

:state(collapsed) {
  opacity: 0;
}
```

**Comment by nkbt** [comment]
```css
.button[visible="1"] {
  color: blue;
}

.button[collapsed="1"] {
  opacity: 0;
}
```

**Comment by andreypopp** [comment]
Also though about similar thing.

But with a different syntax:
```
.name {
  ...
}
.name:state(visible) {
  ...
}
```
generates the following CSS:
```
.<uniqid> {
  ...
}
.<uniqid>--visible {
  ...
}
```
and the following JS:
```
module.exports = {
  name(state = {}) {
    let className = '<uniqid>';
    if (state.visible) {
      className += '<uniqid>--visible';
    }
    return className;
  }
}
```

**Comment by nkbt** [comment]
Speaking in general I prefer the idea of managing "state"-styling through JS, rather then CSS and use CSS only for "theme"-styling. So our styling is separated by actual concerns.

**Comment by rafaelrinaldi** [comment]
@nkbt The whole point is not to mess with DOM attributes but local variables/properties instead (which is where CSS Modules excels at).

A more detailed example:

```css
.root {
  font-family: sans-serif;
  color: white;
  background: fuchsia;
}

:state(collapsed) {
  opacity: 1;
}
```

```js
import styles from './component.css';

styles.state.collapsed; // {opacity: 1}

// or maybe
import { styles, state } from './component.css';

state.collapsed; // {opacity: 1}
```

Also, I get your idea of theme (which I prefer calling layout) vs. styling but the concerns you see doesn't make much sense to me TBH. It's your personal preference and not something that's implied.

@andreypopp That's kind of the same idea indeed! I just wanted to take full advantage of CSS Modules, so I really don't care how the class name looks like after the build process, I just want to have access to it on my properties hash.

---

I have mixed feelings about all that. It might be a silly idea, but I just wanted to hear from others so thanks @nkbt and @andreypopp :)
