### ISSUE TITLE
how to apply adjacent selectors?

### ISSUE THREAD

**Issue by ctaepper** [css-modules/css-modules#69]
say i have the class `.form-row` which is applied to multiple divs within a `.form`

``` css
.form {
    display: flex;
    flex-direction: column;
}
.form-row {
    composes: top-margin-large from 'styles/margins.css';
}
```

every row now has a top margin, also the first row. In regular css i would say

```
.form-row + .form-row {
    margin-top: 20px;
}
```

in css-modules i can workaround using 

``` css
.form-row:first-child {
    margin-top: 0;
}
```

but i don't think this is the philosophy behind css-modules?
**whats the best way to do this?**

http://www.w3.org/TR/CSS21/selector.html#adjacent-selectors

**Comment by geelen** [comment]
Actually I think this is a great way to do it. This is one of the times when keeping the power of normal CSS really pays off. The only thing CSS Modules would "recommend" would be thinking about whether you can express the margin behaviour in a reusable way. A couple of alternatives:

```css
/* margins.css */
.top-margin-large {
  margin-top: 20px;
}
.no-margin-on-first:first-child {
  margin: 0;
}

/* form.css */
.form-row {
  composes: top-margin-large no-margin-on-first from './margins.css';
}
```

Alternatively, to be able to use the `+` selector:

```css
/* margins.css */
.margin-large-between-siblings + .margin-large-between-siblings {
  margin-top: 20px;
}

/* form.css */
.form-row {
  composes: margin-large-between-siblings from './margins.css';
}
```

If you're going to reuse that behaviour elsewhere to give a consistent rhythm between vertical elements, give it a general name. If not, use it like a normal CSS and don't try to `compose` the `:first-child` bit. With the upcoming `@value` keyword (soon I promise!) you'll have even more options: https://github.com/css-modules/postcss-modules-values
