### ISSUE TITLE
best practices regarding media queries

### ISSUE THREAD

**Issue by ctaepper** [css-modules/css-modules#75]
so, obviously i cant compose within media queries, i have to define the query dependent differences within the base classes. however i cant figure out a "good way" to do so.

lets say i have defined a base class
```css
/* margins.css */
.large-margin {
  margin: 20px;
}
```
and i have a module 
```css
.box {
  composes: large-margin from 'margins.css';
}
```
now i want that box to have only 5px of margin for media(max-width: 400px). i cant compose `.box` differently inside a media query, css modules don't work that way so i guess i need put the media query on `.large-margin`, for example
```css
@media (max-width: 400px) {
  .large-margin {
    margin: 5px;
  }
}
```
but now i redefined large-margin for the whole page. what if i still need this large-margin to be 20px at other places? i only what that specific box to have 5px instead of 20px?

the only solution i can think of now is to have a different .box class applied to the box via javascript, if the viewport changes to less than 400px? but this looks like an awfull workaround?

**Comment by Undistraction** [comment]
Can't large-margin contain the media query already (using Sass for brevity):

```
.large-margin {
  margin: 20px;

  @media (max-width: 400px) {
    margin: 5px;
  }
}
```

Obviously you might want a separate class for a fixed large margin and this adaptive margin.

**Comment by ctaepper** [comment]
@Undistraction i would love to do it exactly this way, but you can only compose at classname level, not within pseudoselectors or mediqueries

**Comment by joeybaker** [comment]
@ctaepper I think `@values` might be a better match for you than composes. I think @geelen pointed you that direction for a similar problem in https://github.com/css-modules/css-modules/issues/69

**Comment by Undistraction** [comment]
@ctaepper Ah. Apologies. Just wrapping my head round this project at the moment.

**Comment by joeybaker** [comment]
Of course! I find composes is really good for sharing many styles. Simple things like margins and colors can be more "variable" based.

**Comment by geelen** [comment]
Yeah, I'd probably do what @Undistraction is suggesting but using `@value` (which is already in css-loader for webpack but not officially "launching" until I get a blog post written about it — this weekend's goal).

I'd do something like this:

```css
/* margins.css */
@value small as bp-small from "./breakpoints.css";

@value L: 20x;
@value S: 5px;

.large {
  margin: L;
}

.small {
  margin: S;
}

.adaptive {
  margin: L;
}
@media(bp-small) {
  .adaptive {
    margin: S;
  }
}
```

Then you can write:

```css
/* component.css */
@value margins: "./margins.css"

.foo {
  composes: adaptive from margins;
}
```

Or, if you prefer


```css
/* component.css */
@value adaptive as adaptive-margin from "./margins.css";

.foo {
  composes: adaptive-margin;
}
```

`@value`s are pretty flexible, so use what ever style you prefer.

**Comment by kawing-chiu** [comment]
@geelen Hi. Has your blog post already come out? I can't figure out how to make `@value` work using webpack/css-loader.

**Comment by Ajar-Ajar** [comment]
+1 - @geelen - Any chance you'll be posting that blog post or official documentation on @value anytime soon? Anything we can do to help speed things up?
Cheers
Ajar

**Comment by axelson** [comment]
Is there documentation of `@value` anywhere?

**Comment by joshwnj** [comment]
@axelson there's this: https://github.com/css-modules/postcss-modules-values

Are there things not covered there that you're looking for?

**Comment by axelson** [comment]
Well, it's not documented anywhere that postcss-modules-values is included as part of css-modules. Also postcss-modules-values doesn't appear ready for prime-time yet (as in it's not possible to do many things that I would expect would be possible). Can we at least get a link in the README to postcss-modules-values?

**Comment by ctaepper** [comment]
In the meantime, i am using the postcss-cssnext plugin... It provides native variables, which can do everything I tried to achieve with @value's

**Comment by oyeanuj** [comment]
In the above example by @geelen, it seems like we can't do the following:
```css
/* component.css */
@value adaptive, non-adaptive from "./margins.css";

.foo {
   composes: non-adaptive;
  @media only screen and (min-width: 1024px) {
    composes: adaptive-margin;
  }
}
```

Is that a accurate limitation? Or something that I am missing?

**Comment by ctaepper** [comment]
@oyeanuj composing basically means, the composed class will be added to the element. this is not possible by media query or pseudo selector... you will have to add the media query to the original class that gets added by being composed

**Comment by jettangs** [comment]
@geelen should not write () outside the value imported.Should be:
`@media phone` not `@media (phone)`

**Comment by lonelydatum** [comment]
I struggled with this as well because I wasn't sure what the content was for 
/* breakpoints.css */

I found this site helpful:
https://npm.taobao.org/package/postcss-modules-values

/* breakpoints.css */
@value small: (max-width: 599px);
@value medium: (min-width: 600px) and (max-width: 959px);
@value large: (min-width: 960px);

**Comment by receter** [comment]
This did the job for me: 

```css
/* breakpoints.css */
@value desktop-up: min-width: 975px;
```
```css
/* module1.css */
@value desktop-up from './breakpoints.css';
@media (desktop-up) {
  .myClass {
    margin: 42px;
  }
}
```

`@value small: (max-width: 599px);` and `@media small` was causing more linter issues VS:
`@value small: max-width: 599px;` and `@media (small)`
