### ISSUE TITLE
@import * as foo from 'somewhere.css'

### ISSUE THREAD

**Issue by tf** [css-modules/css-modules#82]
When using multiple classes from an imported stylesheet it becomes cumbersome to always have to repeat the file name:

```css
.edit-button {
  composes: edit-icon from "../icons/something.css";
}

.delete-button {
  composes: delete-icon from "../icons/something.css";
}

.publish-button {
  composes: publish-icon from "../icons/something.css";
}
```

Instead, I think it would be much DRYer if there was something like:

```css
@import * as icons from "../icons/something.css";

.edit-button {
  composes: edit-icon from icons;
}

.delete-button {
  composes: delete-icon from icons;
}

.publish-button {
  composes: publish-icon from icons;
}
```

[CSS modules values](https://github.com/css-modules/postcss-modules-values) already support aliasing a file name like that:

```css
@value colors: "./colors.css";
@value primary, secondary from colors;
```

I'm not sure if overloading `@import` like that would be evil, but it fits right in with ES6 imports.

Thoughts?

**Comment by geelen** [comment]
You can define a `@value` as a string, so:

```css
@value icons: "../icons/something.css";
```

Then the syntax you suggest is already possible:

```css
.edit-button {
  composes: edit-icon from icons;
}

.delete-button {
  composes: delete-icon from icons;
}

.publish-button {
  composes: publish-icon from icons;
}
```
