### ISSUE TITLE
how do I use postcss-simple-vars to add sass like variables in css modules

### ISSUE THREAD

**Issue by jameszmartin** [css-modules/css-modules#92]
I was wanting to add variables to my project, for instance a colors.css file

**colors.css**

``` css
$blue: #cee3f6;
$red: #ff0000;
```

I am using [postcss-simple-vars](https://github.com/postcss/postcss-simple-vars) instead of precss as I don't need any other sass features. 

**header.css**

``` css
@import "./styles/colors";

.header {
  color: $blue;
  background-color: $red;
}
```

It doesn't seem to be working for me like that coming up with `module is undefined` error

**Comment by StevenIseki** [comment]
Hey James, seeing as we both just worked this out, I will post the answer for others to look at.

Although we still haven't worked out how to do it with postcss-simple-vars, instead found it was much easier to just use @geelen [postcss-modules-values](https://github.com/css-modules/postcss-modules-values) plugin and export the variables as values.

**colors.css**

```
@value blue: #0c77f8;
@value red: #ff0000;
@value white: #fff;
```

**header.css**

```css
@value colors: "./colors.css";
@value blue, white, red, green from colors;

.header {
  color: $blue;
  background-color: $red;
}
```

Also working on a [css-module-npm-boilerplate](https://github.com/StevenIseki/css-module-npm-boilerplate) repo as an example for publishing reusable css modules to npm. As we have been doing this so far in our project.
